#!/usr/bin/env python3
"""The Sonic VFX test matrix (02-brief-vfx-expansion.md §20-21): every scene through every input class, measured.

    python3 tools/sonic_vfx/matrix.py run <scene-id> [class ...] [--projects DIR] [--out DIR] [--size 480x270]
    python3 tools/sonic_vfx/matrix.py report [--out DIR] [--md docs/prototypes/sonic-garden/TEST-MATRIX.md]

`run` renders each class's clip with its audio (the file path: the same character, context and response as live,
ADR-1025), writes the pinned engine's signal trace, and runs the evaluator (tools/sonic_vfx_critic.py measure) on
it. `report` gathers every report under --out into the matrix: per scene and class, what the scene's vocabulary
expects of that input, what the picture was measured to answer (signals at z >= 3, with event latency), the
evaluator's scores, and its findings.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, REPO)
from tools.sonic_vfx import review  # noqa: E402

# What each input class exercises: the signals the vocabulary rows for that class should answer.
CLASS_EXPECTS = {
    "pads": ["response.sustain", "notes.polyphony", "notes.tension", "notes.held"],
    "chords": ["notes.polyphony", "notes.tension", "response.note"],
    "bass": ["response.bass", "response.note", "notes.lastPitch"],
    "lead": ["response.note", "notes.lastPitch", "notes.lastVelocity"],
    "arp": ["response.note", "notes.lastPitch"],
    "edrums": ["response.kick", "response.snare", "response.hat"],
    "drumloop": ["response.kick", "response.snare", "response.hat"],
    "dense": ["response.note", "notes.polyphony", "notes.density", "response.kick", "response.hat"],
    "sparse": ["response.note", "notes.lastPitch"],
    "velocity": ["notes.lastVelocity", "response.note"],
    "rapid": ["response.note", "notes.lastPitch"],
    "sustained": ["response.sustain", "notes.held"],
    "full": ["response.note", "response.bass", "response.kick", "response.snare", "response.hat",
             "response.sustain"],
}


def run(a):
    classes = a.classes or review.CLASSES
    out = os.path.join(a.out, a.scene)
    os.makedirs(out, exist_ok=True)
    for cls in classes:
        proj, dur = review.variant(a.scene, cls, out, a.projects or None)
        base = os.path.join(out, cls)
        if not (a.skip_existing and os.path.exists(base + ".critic.json")):
            review.run(["--headless", "--project", proj, "--render", base + ".mp4", "--range", "0:%.2f" % dur,
                        "--size", a.size, "--fps", a.fps, "--codec", "h264", "--quality", "70",
                        "--particle-warmup", "120", "--tier", a.tier])
            subprocess.run([review.AVGEN, "--project", proj, "--sonic-trace", base + ".trace.csv"],
                           capture_output=True)
            subprocess.run([sys.executable, os.path.join(REPO, "tools", "sonic_vfx_critic.py"), "measure",
                            "--video", base + ".mp4", "--trace", base + ".trace.csv", "--project", proj, "--out",
                            base + ".critic.json"], capture_output=True)
        print(a.scene, cls, "ok" if os.path.exists(base + ".critic.json") else "MISSING")


def vocab_for(doc):
    rows = (doc.get("sonicScene") or {}).get("vocabulary") or []
    return {r[1]: r for r in rows if len(r) > 2 and isinstance(r[1], str) and "." in r[1]}


def observed(rep):
    av = rep.get("measures", {}).get("audioVisual", {})
    hits = []
    for name, r in av.items():
        if r.get("z", 0) >= 3.0 and r.get("r", 0) > 0:
            e = r.get("erp") or {}
            lat = (" %.0f ms" % (1000 * e["latency"])) if e.get("latency") is not None and name.endswith("Env") else ""
            hits.append((r.get("z", 0), "%s (z %.1f%s)" % (name, r["z"], lat)))
    hits.sort(reverse=True)
    return [h for _, h in hits[:6]]


def report(a):
    scenes = sorted(d for d in os.listdir(a.out) if os.path.isdir(os.path.join(a.out, d)))
    lines = ["# Sonic VFX test matrix", "",
             "Every scene through the thirteen input classes of the synthesized test material",
             "(`tools/sonic_vfx/make_test_material.py`), rendered from the file path (the same response, character and",
             "context as live, ADR-1025) and measured by the evaluator (`tools/sonic_vfx_critic.py measure`).",
             "Generated by `tools/sonic_vfx/matrix.py report`; the per-clip reports are in the review folder.", "",
             "- **Expected:** the scene's vocabulary rows that this input exercises (what the scene says the world "
             "does).",
             "- **Observed:** signals the picture measurably answers (synchrony z >= 3), strongest first, with the "
             "event latency for hits.",
             "- **Quality:** the evaluator's mean dimension score (0..1) and its lowest dimension.",
             "- **Problems:** the evaluator's findings for that clip (severity medium and up).", ""]
    pre = os.path.join(a.out, "preamble.md")
    if os.path.exists(pre):        # notes written beside the reports (the material, the detector's limits)
        lines += [open(pre).read().rstrip(), ""]
    for sc in scenes:
        reps = {}
        for p in sorted(glob.glob(os.path.join(a.out, sc, "*.critic.json"))):
            cls = os.path.basename(p).split(".")[0]
            reps[cls] = json.load(open(p))
        if not reps:
            continue
        proj = os.path.join(a.out, sc, "%s--%s.json" % (sc, next(iter(reps))))
        doc = json.load(open(proj)) if os.path.exists(proj) else {}
        vocab = vocab_for(doc)
        lines += ["## %s" % ((doc.get("sonicScene") or {}).get("title") or sc), ""]
        if (doc.get("sonicScene") or {}).get("thesis"):
            lines += ["*%s*" % doc["sonicScene"]["thesis"], ""]
        lines += ["| input | expected | observed | quality | problems |", "|---|---|---|---|---|"]
        for cls in review.CLASSES:
            r = reps.get(cls)
            if r is None:
                continue
            exp = [vocab[s][2] if len(vocab[s]) > 2 else s for s in CLASS_EXPECTS.get(cls, []) if s in vocab]
            exp_txt = "; ".join(e[:70] for e in exp[:3]) or "(no row of the vocabulary)"
            obs_txt = ", ".join(observed(r)) or "nothing measured"
            sc_ = r.get("scores", {})
            mean = sum(sc_.values()) / max(1, len(sc_))
            low = min(sc_.items(), key=lambda kv: kv[1]) if sc_ else ("-", 0)
            probs = [f["title"] for f in r.get("findings", []) if f.get("severity") in ("medium", "high")]
            lines.append("| %s | %s | %s | %.2f (low: %s %.2f) | %s |" % (
                cls, exp_txt.replace("|", "/"), obs_txt, mean, low[0], low[1], "; ".join(probs[:4]) or "none"))
        lines.append("")
    open(a.md, "w").write("\n".join(lines) + "\n")
    print(a.md)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["run", "report"])
    ap.add_argument("scene", nargs="?")
    ap.add_argument("classes", nargs="*")
    ap.add_argument("--projects", default="")
    ap.add_argument("--out", default=os.path.expanduser("~/Desktop/av-gen-review/25-sonic-vfx/matrix"))
    ap.add_argument("--size", default="480x270")
    ap.add_argument("--fps", default="24")
    ap.add_argument("--skip-existing", action="store_true")
    ap.add_argument("--tier", default="realtime")
    ap.add_argument("--md", default=os.path.join(REPO, "docs", "prototypes", "sonic-garden", "TEST-MATRIX.md"))
    a = ap.parse_args()
    if a.mode == "run":
        run(a)
    else:
        report(a)


if __name__ == "__main__":
    main()
