// THE RIFT (proto/bioluminescent): the first Environment's projects are generated by examples/bioluminescent/build.py,
// and presets ignore paths that are not parameters (params::applyPreset), silently: a stage that names a path the
// engine does not have simply does nothing. This is the scene's own guard -- every preset path, route target and
// macro target of both projects is a parameter of the loaded engine, the ecosystem's layers and the excitable medium
// reached the scene, and the arc has its stages. Rerun build.py after changing it, then this.

#include "app/engine.hpp"
#include "params/modulation.hpp"
#include "params/preset.hpp"
#include "scene/scene.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <string>
#include <vector>

using namespace avgen;
namespace fs = std::filesystem;

TEST_CASE("THE RIFT: every preset path, route target and macro target is a parameter", "[rift]") {
    for (const char* name : {"rift.json", "rift-live.json"}) {
        const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/bioluminescent" / name;
        app::Engine engine(app::EngineMode::Offline);
        auto loaded = engine.loadProject(project);
        INFO(project.string() << (loaded ? "" : (": " + loaded.error().message)));
        REQUIRE(loaded.has_value());
        std::vector<std::string> missing;
        for (const params::Preset& preset : engine.presets().presets()) {
            for (const auto& [path, values] : preset.values) {
                if (engine.params().find(path) == nullptr) {
                    missing.push_back("preset " + preset.name + ": " + path);
                }
            }
        }
        for (const params::ModRoute& route : engine.modulator().routes()) {
            // The composition's four default routes are zeroed on purpose and do not exist in this world.
            if (route.amount == 0.0f) {
                continue;
            }
            if (engine.params().find(route.target) == nullptr) {
                missing.push_back("route " + route.source + " -> " + route.target);
            }
        }
        for (const app::WorldMacro& macro : engine.worldMacros()) {
            for (const auto& target : macro.targets) {
                if (engine.params().find(target.path) == nullptr) {
                    missing.push_back("macro " + macro.name + ": " + target.path);
                }
            }
        }
        std::string list;
        for (const std::string& m : missing) {
            list += "  " + m + "\n";
        }
        INFO(name << " names " << missing.size() << " path(s) that are not parameters:\n" << list);
        CHECK(missing.empty());
        CHECK(engine.presets().presets().size() >= 12);

        // The Environment reached the scene: the ecosystem's layers with their templates, and the medium.
        FrameTime t{};
        t.renderTime = 0.0;
        engine.update(t);
        const scene::Scene& s = engine.scene();
        CHECK(s.ecosystem.active());
        CHECK(s.ecosystem.layers.size() >= 8);
        for (const scene::EmitterLayer& l : s.ecosystem.layers) {
            INFO("layer " << l.name);
            REQUIRE(l.points);
            CHECK_FALSE(l.points->empty());
        }
        const auto grid = std::find_if(s.fields.grids.begin(), s.fields.grids.end(),
                                       [](const spatial::GridField& g) { return g.name == "prop"; });
        REQUIRE(grid != s.fields.grids.end());
        CHECK(grid->mode == spatial::GridMode::Excitable);
        CHECK(engine.params().find("ecosystem/plankton/excitedIntensity") != nullptr);
        CHECK(engine.params().find("grid/prop/waveSpeed") != nullptr);
    }
}
