// THE RIFT (proto/bioluminescent): the first Environment's projects are generated by examples/bioluminescent/build.py,
// and presets ignore paths that are not parameters (params::applyPreset), silently: a stage that names a path the
// engine does not have simply does nothing. This is the scene's own guard -- every preset path, route target and
// macro target of both projects is a parameter of the loaded engine, the ecosystem's layers and the excitable medium
// reached the scene, and the arc has its stages. Rerun build.py after changing it, then this.

#include "app/engine.hpp"
#include "params/modulation.hpp"
#include "params/preset.hpp"
#include "scene/scene.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <string>
#include <vector>

using namespace avgen;
namespace fs = std::filesystem;

TEST_CASE("THE RIFT: every preset path, route target and macro target is a parameter", "[rift]") {
    for (const char* name : {"rift.json", "rift-live.json"}) {
        const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/bioluminescent" / name;
        app::Engine engine(app::EngineMode::Offline);
        auto loaded = engine.loadProject(project);
        INFO(project.string() << (loaded ? "" : (": " + loaded.error().message)));
        REQUIRE(loaded.has_value());
        std::vector<std::string> missing;
        for (const params::Preset& preset : engine.presets().presets()) {
            for (const auto& [path, values] : preset.values) {
                if (engine.params().find(path) == nullptr) {
                    missing.push_back("preset " + preset.name + ": " + path);
                }
            }
        }
        for (const params::ModRoute& route : engine.modulator().routes()) {
            // The composition's four default routes are zeroed on purpose and do not exist in this world.
            if (route.amount == 0.0f) {
                continue;
            }
            if (engine.params().find(route.target) == nullptr) {
                missing.push_back("route " + route.source + " -> " + route.target);
            }
        }
        for (const app::WorldMacro& macro : engine.worldMacros()) {
            for (const auto& target : macro.targets) {
                if (engine.params().find(target.path) == nullptr) {
                    missing.push_back("macro " + macro.name + ": " + target.path);
                }
            }
        }
        std::string list;
        for (const std::string& m : missing) {
            list += "  " + m + "\n";
        }
        INFO(name << " names " << missing.size() << " path(s) that are not parameters:\n" << list);
        CHECK(missing.empty());
        CHECK(engine.presets().presets().size() >= 12);

        // The Environment reached the scene: the ecosystem's layers with their templates, and the medium.
        FrameTime t{};
        t.renderTime = 0.0;
        engine.update(t);
        const scene::Scene& s = engine.scene();
        CHECK(s.ecosystem.active());
        CHECK(s.ecosystem.layers.size() >= 8);
        for (const scene::EmitterLayer& l : s.ecosystem.layers) {
            INFO("layer " << l.name);
            REQUIRE(l.points);
            CHECK_FALSE(l.points->empty());
        }
        const auto grid = std::find_if(s.fields.grids.begin(), s.fields.grids.end(),
                                       [](const spatial::GridField& g) { return g.name == "prop"; });
        REQUIRE(grid != s.fields.grids.end());
        CHECK(grid->mode == spatial::GridMode::Excitable);
        CHECK(engine.params().find("ecosystem/plankton/excitedIntensity") != nullptr);
        CHECK(engine.params().find("grid/prop/waveSpeed") != nullptr);
    }
}

// ADR-1168 on THE RIFT: an offline seek must land the arc where a play from zero has it. Found by a `--range 84:112`
// render that sat in the initial state (Dark) through the drop.
TEST_CASE("THE RIFT: a seek lands the arc where play does", "[rift][adr1168]") {
    const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/bioluminescent/rift.json";
    app::Engine engine(app::EngineMode::Offline);
    REQUIRE(engine.loadProject(project).has_value());
    engine.seekSeconds(100.0);
    FrameTime t{};
    t.renderTime = 100.0;
    t.deltaTime = 0.0;
    engine.update(t);
    INFO("state after a seek to 100 s: '" << engine.states().current() << "' (index " << engine.states().currentIndex()
                                          << ")");
    CHECK(engine.states().current() == "Drop");
}

TEST_CASE("THE RIFT: a seek to 84 s then playing on lands in the drop", "[rift][adr1168]") {
    const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/bioluminescent/rift.json";
    app::Engine engine(app::EngineMode::Offline);
    REQUIRE(engine.loadProject(project).has_value());
    engine.seekSeconds(84.0);
    const double fps = 15.0;
    std::string at90, at100;
    for (int k = 0; k <= static_cast<int>(16.0 * fps); ++k) {
        FrameTime t{};
        t.renderTime = 84.0 + k / fps;
        t.deltaTime = k == 0 ? 0.0 : 1.0 / fps;
        t.frameIndex = static_cast<std::uint64_t>(k);
        engine.update(t);
        if (k == static_cast<int>(6.0 * fps)) at90 = engine.states().current();
        if (k == static_cast<int>(16.0 * fps)) at100 = engine.states().current();
    }
    INFO("at 90 s '" << at90 << "', at 100 s '" << at100 << "'");
    CHECK(at100 == "Drop");
}

TEST_CASE("THE RIFT: the render job's sequence (warm-up, camera reset, seek, fixed clock) lands in the drop",
          "[rift][adr1168]") {
    const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/bioluminescent/rift.json";
    app::Engine engine(app::EngineMode::Offline);
    REQUIRE(engine.loadProject(project).has_value());
    // as RenderJob::begin does
    FixedStepClock warm(15.0);
    warm.restartAt(100.0);
    engine.seekSeconds(100.0);
    engine.update(engine.tick(warm));
    const std::string afterWarm = engine.states().current();
    engine.resetCameraState();
    FixedStepClock clock(15.0);
    clock.restartAt(100.0);
    engine.seekSeconds(100.0);
    const std::string afterSeek = engine.states().current();
    engine.update(engine.tick(clock));
    INFO("after the warm-up '" << afterWarm << "', after the second seek '" << afterSeek << "', after the first frame '"
                               << engine.states().current() << "'");
    CHECK(engine.states().current() == "Drop");
}

// The full Trench run's camera parked at the end of its open spline at about 200 s (the flight ran out of path) and
// lost its aim: single frames pointed anywhere (the Critic's "camera shake" at 201-207 s, 14% of the frame per frame).
// The flight must fit the track: the integrated splineT stays inside the path for the whole song.
TEST_CASE("THE RIFT: the flight does not run out of path before the track ends", "[rift]") {
    const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/bioluminescent/rift.json";
    app::Engine engine(app::EngineMode::Offline);
    REQUIRE(engine.loadProject(project).has_value());
    const auto* t = dynamic_cast<const params::Parameter<float>*>(engine.params().find("camera/splineT"));
    REQUIRE(t != nullptr);
    const double fps = 15.0;
    const double end = 207.6;
    float last = 0.0f;
    for (int k = 0; k <= static_cast<int>(end * fps); ++k) {
        FrameTime ft{};
        ft.renderTime = k / fps;
        ft.deltaTime = k == 0 ? 0.0 : 1.0 / fps;
        ft.frameIndex = static_cast<std::uint64_t>(k);
        engine.update(ft);
        last = t->value();
    }
    INFO("camera/splineT at " << end << " s: " << last);
    CHECK(last < 0.97f);
}
