// DIGITAL MOSH (proto/digital-mosh): the scene's projects are generated by examples/digital-mosh/build.py, and
// presets ignore paths that are not parameters (params::applyPreset), silently. A stage that names a path the engine
// does not have simply does nothing -- which is how a renamed parameter would quietly remove a stage's look. This
// test is the scene's own guard: every preset path, route target and macro target of every DIGITAL MOSH project is a
// parameter of the loaded engine. Rerun build.py after changing it, then this.

#include "app/engine.hpp"
#include "params/modulation.hpp"
#include "params/preset.hpp"

#include <catch2/catch_test_macros.hpp>

#include <filesystem>
#include <string>
#include <vector>

using namespace avgen;
namespace fs = std::filesystem;

TEST_CASE("DIGITAL MOSH: every preset path, route target and macro target is a parameter", "[digital-mosh]") {
    for (const char* name : {"digital-mosh.json", "digital-mosh-trench.json", "digital-mosh-live.json"}) {
        const fs::path project = fs::path(AVGEN_SOURCE_DIR) / "examples/digital-mosh" / name;
        app::Engine engine(app::EngineMode::Offline);
        auto loaded = engine.loadProject(project);
        INFO(project.string() << (loaded ? "" : (": " + loaded.error().message)));
        REQUIRE(loaded.has_value());
        std::vector<std::string> missing;
        for (const params::Preset& preset : engine.presets().presets()) {
            for (const auto& [path, values] : preset.values) {
                if (engine.params().find(path) == nullptr) {
                    missing.push_back("preset " + preset.name + ": " + path);
                }
            }
        }
        for (const params::ModRoute& route : engine.modulator().routes()) {
            if (engine.params().find(route.target) == nullptr) {
                missing.push_back("route " + route.source + " -> " + route.target);
            }
        }
        for (const app::WorldMacro& macro : engine.worldMacros()) {
            for (const auto& target : macro.targets) {
                if (engine.params().find(target.path) == nullptr) {
                    missing.push_back("macro " + macro.name + ": " + target.path);
                }
            }
        }
        std::string list;
        for (const std::string& m : missing) {
            list += "  " + m + "\n";
        }
        INFO(name << " names " << missing.size() << " path(s) that are not parameters:\n" << list);
        CHECK(missing.empty());
        // The stages exist and the machine starts in the Dream.
        CHECK(engine.presets().presets().size() >= 7);
    }
}
