#pragma once

// Modulation routes: signal -> chain -> amount -> op -> (depth) -> parameter component (ADR-011,
// ADR-900).

#include "core/error.hpp"
#include "params/parameter_set.hpp"
#include "params/processor.hpp"
#include "signals/signal_bus.hpp"

#include <cstdint>
#include <functional>
#include <set>
#include <string>
#include <vector>

namespace avgen::params {

namespace liveness {
class Facts;
}

enum class ModOp : std::uint8_t { Add, Multiply, Replace, Min, Max };
enum class Polarity : std::uint8_t { Unipolar, Bipolar }; // Bipolar maps the source 0..1 -> -1..1 before the chain

struct ModRoute {
    std::string source;            // signal name, e.g. "audio.bass"
    std::string target;            // parameter path, e.g. "orb/scale"
    int component = -1;            // -1 = all components
    float amount = 1.0f;           // bipolar; negative inverts
    ModOp op = ModOp::Add;
    Polarity polarity = Polarity::Unipolar;
    ProcessorChain chain{};
    bool enabled = true;
    // ADR-900: the route's depth follows a signal. What the route does to its target -- the distance
    // between the value its op writes and the value the target had before it -- is scaled by
    //   depth = depthMin + (depthMax - depthMin) * value(depthSource)
    // so an Add route's offset and a Multiply route's deviation from 1 both scale, and a depth of 0
    // leaves the target exactly as the route found it. Empty = full depth always: the route applies
    // exactly as a route did before this existed. Stateless -- a function of this frame's signal --
    // so a seek lands where a play does whenever the depth signal itself does (ADR-091).
    std::string depthSource;
    float depthMin = 0.0f;
    float depthMax = 1.0f;
    // ADR-924: the Director plan item that made this route, "<planId>/<itemKey>"; empty for a route a
    // person or a subsystem made. Saved with the route (and only when set), so the Modulation panel can
    // say which plan item made it and why, and the plan's next revision can find it again -- its
    // `produced` entry names exactly this. It changes nothing the route does.
    std::string planItem;

    // Runtime (not serialised)
    bool fromGraph = false;        // installed by a procedural graph evaluation (ADR-028)
    bool fromEntity = false;       // compiled from an entity's `reactions` block (ADR-088)
    // ADR-522: generated by a world macro (`app::WorldMacro::routes`). Third in a family whose
    // first two members were each added after the same defect was found: `loadProject` replaces
    // the AUTHORED routes, and a route a subsystem installed is not authored, so without a flag
    // saying so it is deleted by the pass that reloads the document. Macro routes were being
    // installed, bound, and erased thirty lines before the log line that counts them -- so every
    // world macro in every project in this repository was a knob that moved nothing.
    bool fromMacro = false;
    // Spatial depth (ADR-097). A music influence field scales the depth of the reactions an entity
    // already has rather than adding a second reactivity system beside them, and *this* is where
    // that lands: the field pass writes a gain here once a frame, and it multiplies `amount`
    // exactly as `amount` multiplies the chain. 1 means "no field reaches this route", which is
    // every route in every scene that has no fields in it.
    float spatialGain = 1.0f;
    // Which entity's `reactions` block produced this route, as an index into EntityWorld. The
    // field pass needs to find its own routes, and a route erased and re-added by a rebuild cannot
    // be found by position.
    static constexpr std::uint32_t kNoOwner = 0xFFFFFFFFu;
    std::uint32_t ownerEntity = kNoOwner;
    ProcessorChain::State state{};
    signals::SignalId sourceId = signals::kInvalidSignal;
    signals::SignalId depthId = signals::kInvalidSignal; // ADR-900; invalid when depthSource is empty
    IParameter* targetParam = nullptr;
    float lastOutput = 0.0f;       // for UI display
};

class Modulator {
public:
    ModRoute& addRoute(ModRoute route);
    void clearRoutes();
    [[nodiscard]] std::vector<ModRoute>& routes() { return routes_; }
    [[nodiscard]] const std::vector<ModRoute>& routes() const { return routes_; }

    // Resolves source/target names. Unresolvable routes are reported and skipped by evaluate()
    // until a later bind() resolves them; their `enabled` flag is left alone.
    //
    // ADR-902: and puts every route it resolves through the liveness rules
    // (`liveness::Registry::standard()`), logging each problem once for the life of the modulator --
    // an unresolved route included, which used to be logged again by every rebind. With no facts
    // installed the rules see only the bus and the parameter set (the chain, the source's kind);
    // the engine installs facts that know its scene (`setLivenessFacts`).
    [[nodiscard]] Result<void> bind(const signals::SignalBus& bus, ParameterSet& params);
    [[nodiscard]] bool bound() const { return bound_; }

    // ADR-902. Not owned; must outlive the modulator's binds (null = the bus and parameters only).
    void setLivenessFacts(const liveness::Facts* facts) { facts_ = facts; }
    [[nodiscard]] const liveness::Facts* livenessFacts() const { return facts_; }
    // Records `key` and returns true the first time it is seen: the log-once set bind() uses, shared
    // so that a host reporting the same finding at project load does not report it a second time.
    bool firstReport(const std::string& key) { return reported_.insert(key).second; }

    // params.resetFinals(), then applies every enabled bound route in op-priority order
    // (Replace, Multiply, Add, Min, Max).
    void evaluate(const signals::SignalBus& bus, ParameterSet& params, double dt);
    // The route half of evaluate() without the reset, so a caller can run automation (the
    // timeline) between resetFinals() and the routes.
    void applyRoutes(const signals::SignalBus& bus, ParameterSet& params, double dt);
    // ADR-870: the same pass over only the routes `pick` accepts, in the same op order. A route
    // whose source is not on `bus` is skipped -- a seek replay's bus carries only the deterministic
    // prefix of the engine's signals, and a route reading anything else is not replayed.
    void applyRoutesWhere(const signals::SignalBus& bus, ParameterSet& params, double dt,
                          bool (*pick)(const ModRoute&));

    // ADR-901: runs the chain of every enabled, bound route `pick` accepts on `bus` and writes
    // nothing -- the state a play leaves a route's chain in, advanced through a frame a seek's replay
    // steps without applying the route. A route whose source is not on `bus` is not advanced.
    void advanceChains(const signals::SignalBus& bus, double dt, const std::function<bool(const ModRoute&)>& pick);
    // The chain states of the routes `pick` accepts, in route order, and back (a seek checkpoint).
    [[nodiscard]] std::vector<ProcessorChain::State> chainStates(const std::function<bool(const ModRoute&)>& pick) const;
    void restoreChainStates(const std::function<bool(const ModRoute&)>& pick,
                            const std::vector<ProcessorChain::State>& states);
    void resetChainStates(const std::function<bool(const ModRoute&)>& pick);

    void resetState(); // clears smoothing/envelope/delay state (on seek)

    // Multiplies every route's amount. The UI's "master visualization gain".
    float masterGain = 1.0f;

private:
    std::vector<ModRoute> routes_;
    bool bound_ = false;
    const liveness::Facts* facts_ = nullptr;
    std::set<std::string> reported_;
};

float applyModOp(ModOp op, float current, float modulation);

} // namespace avgen::params
