"""9. 8-BIT OCEAN: BUBBLE REEF (08-brief-8bit-ocean.md; ABSTRACT-PLAN.md section 9).

A lost underwater game level, swum through. The level is a RING round a deep basin with a giant coral tower in its middle,
so the swim never ends: three areas, each with its own palette, one after another -- SUNNY SHALLOWS (blue, cyan and
yellow: brain coral, cyan kelp, a trail of gold coins, the coral arch you enter by), FLOWER RUINS (purple, pink and
turquoise: a colonnade and arches of purple stone, enormous pink flowers, jellies) and PIPE DEEP (deep blue, orange and
green: green pipes, orange branch coral, a shell the size of a house). Fish schools circle the ring, bubbles rise
everywhere, the water's colour changes as you pass from area to area, and THE GUIDE -- a big friendly voxel fish -- swims
the ring the other way, so you meet it every 100 s.

Grammar: the 8-BIT BLOCK and the CHUNKY PRIMITIVE. The sea floor, the rock walls, the kelp, the branch coral, the rocks and
the fish are voxel meshes (generated by tools/sonic_vfx/meshes.py: only the faces between a block and water); the rest is
low-segment primitives (eight-sided columns, ten-sided pipes, low-poly balls, a spiral shell). Two-band toon light from
the surface, thin navy outlines, blue depth haze, light shafts, a checker of blocks on the floor (geometry: two meshes
of alternate blocks, two colours). Original shapes throughout: no game's assets.

THE LIVING LEVEL: the bass bends every kelp plant at once; a melody lights a row of bell flowers note by note (the
twelve pitch classes, one row per area, like a xylophone); a chord blooms every brain coral; drums release swarms of
bubbles and set the coins and gems flashing; the highs sparkle; the fish schools turn on the snare.
"""
import math
import os

from .. import kit
from .. import meshes as mx
from ..kit import R, M, hexrgb, mix, scale3, SLOW, MEDIUM, FAST, HIT, VERY_SLOW

ID = "bit-ocean"
TITLE = "8-Bit Ocean"

RC = 118.0                # the swim's circle (the camera)
LANE = 16.0               # half-width of the clear lane round the circle
PERIOD = 150.0            # one lap of the level (about 5 m/s)
THETA0 = 0.06             # where the lap starts (radians from the first area's beginning)
CELL = 3.0                # the voxel floor's block
# THE GUIDE: a big friendly voxel fish that swims the ring the other way, so the swimmer meets it once every 100 s
GUIDE_CELL = 1.4          # its blocks
GUIDE_R = RC + 24.0       # it passes on the swimmer's right, outside the lane
GUIDE_Y = 19.0
GUIDE_PERIOD = 300.0      # its lap, against the swim: the two meet every 1 / (1/150 + 1/300) = 100 s
GUIDE_AHEAD_AT_6 = 22.0   # degrees ahead of the swimmer at 6 s (the hero still): it passes alongside at 12 s
MESH_DIR = os.path.join(kit.ABSTRACT_DIR, "meshes")

# the three areas: (name, start angle in degrees, floor, floor alternate, rock, kelp, coral, accent, water colour)
AREAS = [
    ("shallows", 0.0, "#f7c548", "#e9ad2a", "#3d6fd6", "#22d8ff", "#ffcf1f", "#ffe066", "#0e58c8"),
    ("ruins", 120.0, "#8a52e0", "#7440c8", "#5b34b0", "#18e6c8", "#ff4fb0", "#ff8fd0", "#2f22a8"),
    ("deep", 240.0, "#2648c8", "#1d38a8", "#1a2c86", "#4fe03a", "#ff7a1a", "#ffb04a", "#06206e"),
]
SHADOW = (0.06, 0.1, 0.32)
BRICKS = ["#ff8a3a", "#ff6fb0", "#56d85a"]     # the ledges' bricks, per area
LANE_CORAL = ["#ff5a7a", "#2fe8d0", "#ff9a2a"]  # the low coral in the lane, per area

DESIGN = {
    "category": "game world",
    "thesis": "Bubble Reef: a lost 8-bit water level grown into 3D and swum through for ever -- three areas with their own "
              "palettes round a deep basin -- that plays along with the music: the bass bends the kelp, a melody rings "
              "a row of bell flowers, a chord blooms the coral, drums burst bubbles and flash the treasure, and a big "
              "friendly fish you meet on the way swims the melody.",
    "composition": {
        "background": "the giant coral tower across the basin, rock walls and kelp silhouettes in blue depth",
        "midground": "the level: arches, columns, pipes, giant flowers, coral, coins along the lane",
        "foreground": "kelp, rocks and bubbles sliding past the lens",
        "focal": "the next arch or the next landmark ahead on the lane",
        "secondary": ["the guide (a big friendly voxel fish, met every 100 s)", "fish schools", "bell flowers",
                      "the coin trail"],
        "atmosphere": "blue depth haze in each area's own water colour; light shafts; bubbles",
        "post": "a soft bloom; nothing pixelated",
        "camera": "a playful swim along the ring, bobbing and swaying",
    },
    "palette": {"dominant": AREAS[0][8], "secondary": AREAS[0][5], "accent": AREAS[0][6], "highlight": "#ffffff",
                "background_value": "mid (blue water)",
                "saturation": "saturated game colours, three palettes, hard toon bands"},
    "motion": {
        "very_slow": ["the lap through the three areas", "the water's colour changing"],
        "medium": ["the swim", "fish schools circling", "kelp swaying"],
        "fast": ["bell flowers ringing", "coins spinning"],
        "extremely_fast": ["bubble bursts", "sparkles", "treasure flashes"],
    },
    "vocabulary": [
        ["bass", "response.bass", "every kelp plant bends at once; the brain coral pulses; the sunlight swells"],
        ["kick", "response.kick", "the coins and gems flash; a ring ripples out through the water"],
        ["snare", "response.snare", "a swarm of bubbles bursts round you; the fish schools turn and dart"],
        ["hat", "response.hat", "sparkles glint in the water"],
        ["mids", "audio.mid", "the fish swim faster; the bubble streams thicken"],
        ["highs", "audio.treble", "tiny sparkling creatures (sparks) swarm"],
        ["beat", "beat.pulse", "the jellies pump"],
        ["brightness", "sonic.brightness.slow", "the water clears and brightens"],
        ["intensity", "response.intensity", "STRUCTURE: the coral grows as the piece builds"],
        ["pitch class", "notes.class.0", "a row of twelve bell flowers in each area, one per pitch class: a melody rings "
         "them note by note"],
        ["chord", "notes.polyphony", "a chord blooms every brain coral and lights it"],
        ["velocity", "notes.lastVelocity", "how big the bubble burst a note releases is"],
        ["held", "notes.held", "the kelp glows while notes are held"],
        ["mod wheel", "control.modwheel", "STRUCTURE: the depth -- the water darkens and thickens"],
        ["pitch", "notes.lastPitch", "THE GUIDE, a big friendly voxel fish met every 100 s, swims the melody's "
                                     "contour (higher notes lift it); a kick bobs it, the bass beats its tail"],
        ["silence", "(no input)", "the swim goes on; the level idles, swaying"],
    ],
    "tier": "light: voxel meshes and low-segment primitives, toon light, analytic fog, a few hundred bubbles",
}


# ================================================================================================ the level's meshes
def polar(x, z):
    r = math.hypot(x, z)
    th = math.atan2(x, z) % (2.0 * math.pi)       # 0 at +z, increasing towards +x (the swim's direction)
    return r, th


def area_of(th):
    return min(2, int(math.degrees(th) // 120.0))


def floor_height(x, z):
    """In blocks: the lane a shallow trough, rising to terraces either side, walls at the ring's edges, the basin
    falling away inside."""
    r, th = polar(x, z)
    d = abs(r - RC)
    n = mx.fbm(x / 26.0, z / 26.0, 3, 3)
    side = mx.smooth(LANE + 4.0, 58.0, d)
    h = 1.0 + (1.0 if n > 0.64 else 0.0) * (1.0 - side) + (2.0 + 2.6 * n) * side   # the lane one block deep
    if r > RC + 48.0:
        h += 5.0 * mx.smooth(RC + 48.0, RC + 70.0, r) * (0.6 + 0.8 * mx.fbm(x / 14.0, z / 14.0, 9, 2))
    if r < RC - 48.0:
        h -= 6.0 * mx.smooth(RC - 48.0, RC - 66.0, r)
    return int(round(h))


def floor_cells(area):
    cells = set()
    n = int((RC + 80.0) / CELL)
    for i in range(-n, n + 1):
        for k in range(-n, n + 1):
            x, z = (i + 0.5) * CELL, (k + 0.5) * CELL
            r, th = polar(x, z)
            if r < RC - 70.0 or r > RC + 78.0 or area_of(th) != area:
                continue
            h = floor_height(x, z)
            for j in range(min(h, 0) - 1, h):
                cells.add((i, j, k))
    return cells


def kelp_cells(seed, height=11):
    """A kelp plant: a stem of blocks that leans a little as it climbs, leaves alternating left and right."""
    cells = set()
    x = 0
    for j in range(height):
        if mx._hash(seed, j, 3) < 0.18:
            x += 1 if mx._hash(seed, j, 4) < 0.5 else -1
        cells.add((x, j, 0))
        if j > 1 and j % 2 == 0:
            side = 1 if (j // 2) % 2 else -1
            cells.add((x + side, j, 0))
            if mx._hash(seed, j, 5) < 0.5:
                cells.add((x + side, j + 1, 0))
    return cells


def coral_cells(seed):
    """Branch coral: a trunk splitting into blocky branches."""
    cells = {(0, 0, 0), (0, 1, 0)}
    tips = [(0, 1, 0)]
    for g in range(3):
        new = []
        for (x, y, z) in tips:
            for b in range(2):
                dx = 1 if mx._hash(seed, g * 7 + b, x + 9) < 0.5 else -1
                dz = 1 if mx._hash(seed, g * 5 + b, z + 4) < 0.5 else -1
                px, py, pz = x, y, z
                for s in range(2):
                    if s == 0:
                        px += dx if b == 0 else 0
                        pz += dz if b == 1 else 0
                    py += 1
                    cells.add((px, py, pz))
                new.append((px, py, pz))
        tips = new
    return cells


def rock_cells(seed, rx=3, ry=2, rz=3):
    cells = set()
    for i in range(-rx, rx + 1):
        for j in range(0, ry + 1):
            for k in range(-rz, rz + 1):
                e = (i / (rx + 0.5)) ** 2 + (j / (ry + 0.6)) ** 2 + (k / (rz + 0.5)) ** 2
                if e < 1.0 - 0.35 * mx._hash(i + 7, j * 13 + k, seed):
                    cells.add((i, j, k))
    return cells


def fish_tris():
    """A geometric fish facing +z: a diamond body and a fin tail."""
    nose, tail = (0.0, 0.0, 0.75), (0.0, 0.0, -0.55)
    top, bot, l, r = (0.0, 0.42, 0.0), (0.0, -0.36, 0.0), (-0.2, 0.0, 0.05), (0.2, 0.0, 0.05)
    body = [(nose, top, r), (nose, r, bot), (nose, bot, l), (nose, l, top),
            (tail, r, top), (tail, bot, r), (tail, l, bot), (tail, top, l)]
    t0, t1, t2 = (0.0, 0.0, -0.5), (0.0, 0.38, -1.05), (0.0, -0.38, -1.05)
    fin = [(t0, t1, t2), (t0, t2, t1)]
    return body + fin


def guide_cells():
    """THE GUIDE, facing +z in cells of GUIDE_CELL: {part: cells} for an orange body, a cream belly, coral fins, white
    eyes, navy pupils and mouth. One solid: the parts are split out of it, so no face is drawn between two of them."""
    body = set()
    span = {}
    for k in range(-6, 10):                                    # tail root to nose
        u = (k + 6) / 15.0
        f = math.sin(math.pi * (0.1 + 0.84 * u)) ** 0.75
        hh, hw = 0.6 + 3.7 * f, 0.5 + 2.7 * f                  # half-height, half-width (cells)
        span[k] = (hh, hw)
        for j in range(-5, 6):
            for i in range(-4, 5):
                if (i / hw) ** 2 + (j / hh) ** 2 <= 1.0:
                    body.add((i, j, k))
    belly = {c for c in body if c[1] < -0.3 * span[c[2]][0]}
    fins = set()
    for k in range(-10, -6):                                   # the tail: a fork, wider as it goes
        d = -6 - k
        for j in range(-d - 1, d + 2):
            if abs(j) >= d - 1:
                fins.add((0, j, k))
    top = {k: max(j for (i, j, kk) in body if kk == k and i == 0) for k in range(-6, 10)}
    for k, h in ((0, 3), (1, 3), (2, 2), (3, 2), (4, 1)):     # the dorsal fin, a swept sail
        for j in range(1, h + 1):
            fins.add((0, top[k] + j, k - (j - 1)))
    for sgn in (-1, 1):                                        # the pectoral fins, little flaps
        for k in (3, 4):
            w = int(span[k][1])
            fins |= {(sgn * (w + 1), -1, k), (sgn * (w + 2), -2, k - 1)}
    eyes, pupils = set(), set()
    for sgn in (-1, 1):                                        # an eye on each flank, looking forward
        k0 = 6
        w = max(i * sgn for (i, j, kk) in body if kk == k0 and j == 1)
        for j in (1, 2):
            for k in (k0, k0 + 1):
                c = (sgn * max(i * sgn for (i, jj, kk) in body if kk == k and jj == j), j, k)
                eyes.add(c)
        pupils.add((sgn * max(i * sgn for (i, jj, kk) in body if kk == k0 + 1 and jj == 1), 1, k0 + 1))
    nose = max(k for (i, j, k) in body)
    mouth = {(i, -1, max(k for (ii, jj, k) in body if ii == i and jj == -1)) for i in (-1, 0, 1)}
    eyes -= pupils
    solid = body | fins
    parts = {"body": body - belly - eyes - pupils - mouth, "belly": belly - mouth, "fins": fins, "eyes": eyes,
             "pupils": pupils | mouth}
    return solid, parts


def tower_cells():
    """The giant coral tower in the basin: a stacked, branching column."""
    cells = set()
    for j in range(0, 26):
        rad = 4 if j < 8 else (3 if j < 16 else 2)
        for i in range(-rad, rad + 1):
            for k in range(-rad, rad + 1):
                if i * i + k * k <= rad * rad + 1 and mx._hash(i + 31, k + j * 7, 5) > 0.08:
                    cells.add((i, j, k))
    for b, (dx, dz, j0) in enumerate(((1, 0, 9), (-1, 1, 13), (0, -1, 17), (1, 1, 20))):
        x, z = 0, 0
        for s in range(9):
            x += dx if s % 2 == 0 else 0
            z += dz if s % 3 == 0 else 0
            cells.add((x * 1 + dx * 3, j0 + s // 2, z + dz * 3))
    return cells


def generate_meshes():
    for a, area in enumerate(AREAS):
        cells = floor_cells(a)
        for par in (0, 1):   # the checker is geometry: two meshes, two colours (a program on the floor cost 9 ms)
            tris = mx.voxels(cells, CELL, keep=lambda i, j, k, par=par: (i + k) % 2 == par)
            mx.write_faceted(os.path.join(MESH_DIR, "bo-floor-%s%d.glb" % (area[0], par)), tris,
                             "floor%s%d" % (area[0], par))
    for s in range(3):
        mx.write_faceted(os.path.join(MESH_DIR, "bo-kelp%d.glb" % s), mx.voxels(kelp_cells(11 + s, 10 + 2 * s), 1.0,
                                                                              (-0.5, 0.0, -0.5)), "kelp%d" % s)
    mx.write_faceted(os.path.join(MESH_DIR, "bo-coral.glb"), mx.voxels(coral_cells(5), 0.8, (-0.4, 0.0, -0.4)),
                     "coral")
    mx.write_faceted(os.path.join(MESH_DIR, "bo-rock.glb"), mx.voxels(rock_cells(3), 1.6, (-0.8, -0.8, -0.8)), "rock")
    mx.write_faceted(os.path.join(MESH_DIR, "bo-fish.glb"), fish_tris(), "fish")
    ledge = {(i, 0, k) for i in range(-2, 3) for k in range(-1, 1)} | {(i, 1, 0) for i in (-2, 0, 2)}
    mx.write_faceted(os.path.join(MESH_DIR, "bo-ledge.glb"), mx.voxels(ledge, 2.0, (-1.0, -1.0, -1.0)), "ledge")
    mx.write_faceted(os.path.join(MESH_DIR, "bo-tower.glb"), mx.voxels(tower_cells(), 4.0, (-2.0, -8.0, -2.0)),
                     "tower")
    solid, parts = guide_cells()
    o = -0.5 * GUIDE_CELL
    for part, cells in parts.items():
        mx.write_faceted(os.path.join(MESH_DIR, "bo-guide-%s.glb" % part),
                         mx.voxels(solid, GUIDE_CELL, (o, o, o), keep=lambda i, j, k, c=cells: (i, j, k) in c),
                         "guide" + part)


# ================================================================================================ materials, programs
def toon(hexc, bands=2, ambient=0.44, emissive=0.0, rim=0.0, spec=0.0, program=None, emissive_col=None):
    m = {"baseColor": hexrgb(hexc), "emissiveColor": hexrgb(emissive_col or hexc), "emissiveIntensity": float(emissive),
         "roughness": 0.7, "metallic": 0.0,
         "toon": {"bands": bands, "softness": 0.02, "terminator": 0.08, "shadowColor": list(SHADOW),
                  "ambient": ambient, "rimWidth": rim, "rimColor": hexrgb("#e8fbff"),
                  "rimIntensity": 0.8 if rim else 0.0, "specular": spec, "specularSize": 0.14}}
    if program:
        m["program"] = program
    return m


# ================================================================================================ placement helpers
def sector(area, count, radius, jitter=(0.0, 0.0, 0.0), seed=1, margin=6.0):
    """A radial distribution over one area's arc of the ring (counter-clockwise from above, like the swim)."""
    a0 = math.radians(AREAS[area][1] + margin)
    a1 = math.radians(AREAS[area][1] + 120.0 - margin)
    # the engine's xz radial puts angle e at (cos e, 0, -sin e); ours puts theta at (sin theta, 0, cos theta), so
    # e = theta - pi/2 (both increase the same way round)
    d = {"kind": "radial", "count": int(count), "radius": float(radius), "plane": "xz", "orientation": "outward",
         "startAngle": a0 - math.pi / 2.0, "endAngle": a1 - math.pi / 2.0}
    v = {"seed": seed, "randomPosition": list(jitter), "randomRotation": [0.0, math.pi, 0.0],
         "randomUniformScale": 0.25}
    return d, v


def at_angle(deg, r, y=0.0):
    th = math.radians(deg)
    return [r * math.sin(th), y, r * math.cos(th)]


def lane_angle(arc_m):
    """Degrees along the swim for a distance along the lane from the lap's start."""
    return math.degrees(THETA0) + math.degrees(arc_m / RC)


# ================================================================================================ the instrument
KELP = ["kelp%s%d" % (a[0], k) for a in AREAS for k in range(2)]
GUIDE_PARTS = ["body", "belly", "fins", "eyes", "pupils"]
BRAIN = ["brain" + a[0] for a in AREAS] + ["laneBrain" + a[0] for a in AREAS]


def instrument(s):
    """The modulation map (ABSTRACT-PLAN.md section 9)."""
    P = "procedural/%s/"
    # ---- BASS: every kelp plant bends at once (the bend's curvature); the brain coral pulses; the light swells
    for node in KELP:
        s.route(R("bass", P % node + "deform/1/amount", 0.07, attackMs=60, decayMs=700, springHz=1.2,
                  springDamping=0.5))
    for node in BRAIN:
        s.route(R("bass", P % node + "transform/scale", 0.12, attackMs=30, decayMs=300))
    s.route(R("bass", "lights/sun/intensity", 1.2, attackMs=40, decayMs=500))
    # ---- KICK: the coins and gems flash (treasure); a ring ripples out through the water (a shock in the frame)
    for node in ("coins", "gemsruins", "gemsdeep"):
        s.route(R("kick", P % node + "material/emissive", 2.4, attackMs=0, decayMs=260))
    s.route(R("kick", "post/shock/amount", 18.0, threshold="binary", thresholdLevel=0.3, envelope="linearfall",
              envelopeHoldMs=0, envelopeFallPerSecond=1.8),
            R("kick", "post/shock/radius", 1.3, threshold="binary", thresholdLevel=0.3, envelope="linearfall",
              envelopeHoldMs=0, envelopeFallPerSecond=1.8, remapEnabled=True, remapInMin=0.0, remapInMax=1.0,
              remapOutMin=1.0, remapOutMax=0.0))
    # ---- SNARE: a swarm of bubbles bursts round the swimmer; the schools turn and dart (a burst of extra turn)
    s.route(R("snare", "particles/burst/burst", 160.0, threshold="binary", thresholdLevel=0.1))
    for node, sgn in (("schoolA", 1.0), ("schoolB", -1.0), ("schoolC", 1.0)):
        s.route(R("snare", P % node + "transform/rotation", 18.0 * sgn, comp=1, attackMs=0, decayMs=600,
                  springHz=1.6, springDamping=0.45))
    # ---- HAT: sparkles glint; HIGHS: tiny sparkling creatures swarm
    s.route(R("hat", "particles/sparkle/burst", 40.0, threshold="binary", thresholdLevel=0.1),
            R("audio.treble", "particles/sparkle/spawnRate", 600.0, attackMs=20, decayMs=250))
    # ---- MIDS: the fish swim faster (their circling, integrated); the bubble streams thicken
    for node, rate in (("schoolA", 9.0), ("schoolB", -12.0), ("schoolC", 7.0)):
        s.route(R("audio.mid", P % node + "transform/rotation", rate, comp=1, integrate=True, attackMs=80,
                  decayMs=500))
    s.route(R("audio.mid", "particles/bubbles/spawnRate", 500.0, attackMs=60, decayMs=500))
    # ---- BEAT: the jellies pump
    s.route(R("beat", P % "jellies" + "transform/scale", 0.14, comp=1, attackMs=0, decayMs=250))
    # ---- BRIGHTNESS: the water clears and brightens (less haze)
    s.route(R("brightnessSlow", "scene/volumeDensity", -0.004, **SLOW))
    # ---- INTENSITY: STRUCTURE -- the coral grows as the piece builds
    for node in BRAIN + ["coralA", "coralC"]:
        s.route(R("intensity", P % node + "transform/scale", 0.25, **VERY_SLOW))
    # ---- MIDI: twelve bell flowers per area, one per pitch class (a melody rings them note by note); a chord blooms
    # every brain coral; velocity is how big the bubble burst a note releases; held notes make the kelp glow
    for k in range(12):
        s.route(R("notes.class.%d" % k, P % ("bell%d" % k) + "material/emissive", 4.0, depth="lastVelocity",
                  attackMs=0, decayMs=700),
                R("notes.class.%d" % k, P % ("bell%d" % k) + "transform/scale", 0.35, attackMs=0, decayMs=500,
                  springHz=2.0, springDamping=0.4))
    for node in BRAIN:
        s.route(R("polyphony", P % node + "transform/scale", 0.6, attackMs=80, decayMs=900),
                R("polyphony", P % node + "material/emissive", 1.6, attackMs=80, decayMs=900))
    s.route(R("noteOn", "particles/burst/burst", 120.0, depth="lastVelocity", threshold="binary", thresholdLevel=0.05))
    for node in KELP:
        s.route(R("held", P % node + "material/emissive", 0.9, **MEDIUM))
    # ---- THE GUIDE sings along: the pitch lifts it (it swims the melody's contour), a kick bobs it, the bass beats its
    # tail (the body's bend), held notes light its eyes
    for part in GUIDE_PARTS:
        node = "guide" + part.capitalize()
        s.route(R("lastPitch", P % node + "transform/position", 9.0, comp=1, **MEDIUM),
                R("kick", P % node + "transform/position", 1.4, comp=1, attackMs=0, decayMs=350, springHz=2.2,
                  springDamping=0.45),
                R("bass", P % node + "deform/1/amount", 0.022, attackMs=40, decayMs=500, springHz=1.4,
                  springDamping=0.5))
    s.route(R("held", P % "guideEyes" + "material/emissive", 1.6, **MEDIUM))
    # ---- MOD WHEEL: STRUCTURE -- the depth: the water darkens and thickens
    wheel = s.modwheel()
    s.route(R(wheel, "scene/volumeDensity", 0.02, attackMs=200, decayMs=200),
            R(wheel, "lights/sun/intensity", -1.5, attackMs=200, decayMs=200))


# ================================================================================================ the camera
def camera_track(s):
    kp, kt, kr = [], [], []
    steps = 96
    for i in range(steps + 1):
        u = i / steps
        th = THETA0 + 2.0 * math.pi * u
        bob = 1.6 * math.sin(2.0 * math.pi * u * 9.0)
        sway = 5.0 * math.sin(2.0 * math.pi * u * 4.0 + 0.7)            # weave across the lane
        r = RC + sway
        pos = (r * math.sin(th), 12.5 + bob + 2.5 * math.sin(2.0 * math.pi * u * 3.0), r * math.cos(th))
        ahead = th + 42.0 / RC
        look = 8.0 * math.sin(2.0 * math.pi * u * 5.0)                  # glance in and out
        tr = RC + look
        tgt = (tr * math.sin(ahead), 5.0 + 1.5 * math.sin(2.0 * math.pi * u * 7.0), tr * math.cos(ahead))
        kp.append({"time": round(PERIOD * u, 4), "value": [round(v, 3) for v in pos], "interp": "smooth"})
        kt.append({"time": round(PERIOD * u, 4), "value": [round(v, 3) for v in tgt], "interp": "smooth"})
        kr.append({"time": round(PERIOD * u, 4), "value": round(-4.0 * math.cos(2.0 * math.pi * u * 4.0 + 0.7), 3),
                   "interp": "smooth"})
    s.track("camera/position", kp, loop=PERIOD)
    s.track("camera/target", kt, loop=PERIOD)
    s.track("camera/roll", kr, loop=PERIOD)
    s.camera = {"mode": 1, "position": kp[0]["value"], "target": kt[0]["value"], "fov": 55.0, "orbitSpeed": 0.0}
    # the water's colour follows the area the swimmer is in (a smooth change at each border)
    keys = []
    for i in range(37):
        u = i / 36.0
        deg = (math.degrees(THETA0) + 360.0 * u) % 360.0
        a = area_of(math.radians(deg))
        nxt = (a + 1) % 3
        into = (deg % 120.0) / 120.0
        w = mx.smooth(0.86, 1.0, into)
        c = mix(hexrgb(AREAS[a][8]), hexrgb(AREAS[nxt][8]), w)
        keys.append({"time": round(PERIOD * u, 4), "value": c, "interp": "smooth"})
    s.track("scene/fogColor", keys, loop=PERIOD)


# ================================================================================================ build
def build():
    generate_meshes()
    s = kit.Scene(ID, TITLE, DESIGN)
    s.response = {"sensitivity": 0.5, "transient": 0.55, "sustain": 0.55, "attack": 1.0, "release": 1.1,
                  "floorDb": -44.0, "rangeDb": 42.0}     # mastered music does not saturate the levels
    s.environment = {
        "intensity": 0.55, "background": hexrgb(AREAS[0][8]), "fogColor": hexrgb(AREAS[0][8]),
        "volumeDensity": 0.0052, "volumeMaxDistance": 0.0, "skyIntensity": 1.0,
        "sky": {"enabled": True, "zenithColor": hexrgb("#2aa4f4"), "horizonColor": hexrgb("#0d4ab0"),
                "groundColor": hexrgb("#062a6e"), "haze": 0.5, "sunIntensity": 0.0, "intensity": 1.0,
                "background": True, "useKeyLight": False},
    }
    s.light("sun", "directional", direction=[0.3, -0.88, -0.36], color=hexrgb("#fff8e8"), intensity=3.6,
            castsShadow=False)

    # ---- the sea floor, an area at a time (each its own colour), and the tower in the basin
    for a, area in enumerate(AREAS):
        for par in (0, 1):
            s.proc("floor%s%d" % (area[0], par), {"kind": "mesh", "asset": "meshes/bo-floor-%s%d.glb" % (area[0], par)},
                   material=toon(area[2 + par], ambient=0.5))
    s.proc("tower", {"kind": "mesh", "asset": "meshes/bo-tower.glb"},
           material=toon("#ff7a5c", ambient=0.65, rim=0.2),
           transform={"position": [0.0, -16.0, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})

    # ---- kelp on both sides of the lane in every area (a bend about each plant's own base: the bass)
    bend = [{"kind": "bend", "amount": 0.0, "axis": [0.0, 1.0, 0.0], "space": "local"}]
    for a, area in enumerate(AREAS):
        for k, (rad, n) in enumerate(((RC - 25.0, 26), (RC + 26.0, 28))):
            d, v = sector(a, n, rad, jitter=(5.0, 0.0, 10.0), seed=40 + a * 5 + k)
            v["randomScale"] = [0.0, 0.35, 0.0]
            s.proc("kelp%s%d" % (area[0], k), {"kind": "mesh", "asset": "meshes/bo-kelp%d.glb" % ((a + k) % 3)},
                   distribution=d, variation=v, material=toon(area[5], ambient=0.65, emissive_col=area[5]),
                   deformers=bend, extra={"sourceTransform": {"scale": [1.3, 1.6, 1.3]}})

    # ---- floating platforms of bricks either side of the lane (the platformer's ledges), in each area's colour
    for a, area in enumerate(AREAS):
        for k, (rad, hgt) in enumerate(((RC - 22.0, 21.0), (RC + 23.0, 25.0))):
            d, v = sector(a, 7, rad, jitter=(3.0, 4.0, 18.0), seed=150 + a * 3 + k, margin=10.0)
            v["randomRotation"] = [0.0, 0.25, 0.0]
            s.proc("ledge%s%d" % (area[0], k), {"kind": "mesh", "asset": "meshes/bo-ledge.glb"}, distribution=d,
                   variation=v, material=toon(BRICKS[a], ambient=0.55, rim=0.2),
                   transform={"position": [0.0, hgt, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})

    # ---- rocks (blocky clumps) along the lane's edges
    for a, area in enumerate(AREAS):
        d, v = sector(a, 14, RC + (24.0 if a % 2 else -24.0), jitter=(10.0, 0.0, 30.0), seed=60 + a)
        s.proc("rocks" + area[0], {"kind": "mesh", "asset": "meshes/bo-rock.glb"}, distribution=d, variation=v,
               material=toon(area[4], ambient=0.6), transform={"position": [0, 3.5, 0], "rotation": [0, 0, 0],
                                                                  "scale": [1, 1, 1]})

    # ---- brain coral (chunky balls) in every area, in its accent colour (a chord blooms them)
    for a, area in enumerate(AREAS):
        d, v = sector(a, 20, RC + (15.0 if a != 1 else -15.0), jitter=(4.0, 0.0, 14.0), seed=70 + a)
        s.proc("brain" + area[0], {"kind": "sphere", "radius": 3.2, "segments": 8, "rings": 6}, distribution=d,
               variation=v, material=toon(area[6], ambient=0.62, rim=0.25, emissive_col=area[6]),
               transform={"position": [0, 4.5, 0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})

    # ---- low set dressing scattered in the lane itself (the swim passes over it): the foreground's parallax
    for a, area in enumerate(AREAS):
        d, v = sector(a, 22, RC, jitter=(13.0, 0.0, 10.0), seed=170 + a, margin=3.0)
        s.proc("laneCoral" + area[0], {"kind": "mesh", "asset": "meshes/bo-coral.glb"}, distribution=d, variation=v,
               material=toon(LANE_CORAL[a], ambient=0.5, rim=0.25),
               transform={"position": [0.0, 3.0, 0.0], "rotation": [0, 0, 0], "scale": [1.5, 1.5, 1.5]})
        d, v = sector(a, 18, RC, jitter=(14.0, 0.0, 12.0), seed=180 + a, margin=5.0)
        s.proc("laneBrain" + area[0], {"kind": "sphere", "radius": 1.8, "segments": 8, "rings": 6}, distribution=d,
               variation=v, material=toon(area[6], ambient=0.55, rim=0.3, emissive_col=area[6]),
               transform={"position": [0.0, 3.6, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})

    # ---- AREA 1, SUNNY SHALLOWS: the coral arch you enter by, branch coral, the coin trail
    arch_deg = lane_angle(70.0)
    s.proc("arch", {"kind": "torus", "majorRadius": 21.0, "minorRadius": 2.8, "majorSegments": 12, "minorSegments": 5},
           material=toon("#ff8f5a", ambient=0.62, rim=0.2),
           transform={"position": at_angle(arch_deg, RC, 0.0), "rotation": [0.0, arch_deg, 0.0], "scale": [1, 1, 1]},
           extra={"sourceTransform": {"rotation": [0.0, 0.0, 90.0]}})
    s.proc("archStuds", {"kind": "sphere", "radius": 1.8, "segments": 6, "rings": 4},
           distribution={"kind": "radial", "count": 12, "radius": 21.0, "plane": "yz", "orientation": "outward"},
           material=toon("#ffd23a", ambient=0.7),
           transform={"position": at_angle(arch_deg, RC, 0.0), "rotation": [0.0, arch_deg, 0.0], "scale": [1, 1, 1]})
    d, v = sector(0, 10, RC - 22.0, jitter=(10.0, 0.0, 30.0), seed=81)
    s.proc("coralA", {"kind": "mesh", "asset": "meshes/bo-coral.glb"}, distribution=d, variation=v,
           material=toon("#ff6b6b", ambient=0.62), transform={"position": [0, 3.0, 0], "rotation": [0, 0, 0],
                                                              "scale": [2.2, 2.2, 2.2]})
    # the coin trail: a wavy line along the lane through the first area (spinning coins)
    coin_spin = [{"kind": "twist", "amount": 0.0, "speed": 2.6, "phase": 0.0, "axis": [0.0, 1.0, 0.0],
                  "space": "local"}]
    d, v = sector(0, 34, RC, jitter=(0.0, 0.0, 0.0), seed=1, margin=14.0)
    v = {"seed": 3, "randomPosition": [0.0, 0.0, 0.0]}
    s.proc("coins", {"kind": "cylinder", "radius": 1.15, "height": 0.3, "radialSegments": 8, "caps": True},
           distribution=d, material=toon("#ffd23a", ambient=0.8, spec=0.8, emissive=0.45, emissive_col="#ffe066"),
           deformers=coin_spin + [{"kind": "sine", "amount": 3.0, "frequency": 0.09, "speed": 0.0, "phase": 0.0,
                                   "axis": [1.0, 0.0, 0.0], "displacementAxis": [0.0, 1.0, 0.0], "space": "world"}],
           transform={"position": [0.0, 8.0, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]},
           extra={"sourceTransform": {"rotation": [90.0, 0.0, 0.0]}})

    # ---- AREA 2, FLOWER RUINS: a colonnade either side of the lane, arches over it, giant flowers, jellies, gems
    for side, rad in (("In", RC - 18.0), ("Out", RC + 18.0)):
        d, _v = sector(1, 9, rad, margin=12.0)
        s.proc("column" + side, {"kind": "cylinder", "radius": 1.7, "height": 16.0, "radialSegments": 8,
                                 "caps": True}, distribution=d, material=toon("#b48cf0", ambient=0.62, rim=0.15),
               transform={"position": [0.0, 8.0, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})
        s.proc("capital" + side, {"kind": "box", "size": [4.6, 1.6, 4.6], "subdivisions": 1}, distribution=d,
               material=toon("#d6b8ff", ambient=0.7), transform={"position": [0.0, 16.6, 0.0],
                                                                  "rotation": [0, 0, 0], "scale": [1, 1, 1]})
    for k, arc in enumerate((330.0, 390.0, 450.0)):
        deg = 120.0 + 30.0 * (k + 1)
        s.proc("ruinArch%d" % k, {"kind": "torus", "majorRadius": 24.0, "minorRadius": 2.0, "majorSegments": 8,
                                  "minorSegments": 4}, material=toon("#9b74e6", ambient=0.62, rim=0.15),
               transform={"position": at_angle(deg, RC, 0.0), "rotation": [0.0, deg, 0.0], "scale": [1, 1, 1]},
               extra={"sourceTransform": {"rotation": [0.0, 0.0, 90.0]}})
    for k, (deg, rad, hgt) in enumerate(((146.0, RC - 30.0, 30.0), (176.0, RC + 32.0, 38.0), (206.0, RC - 29.0, 26.0),
                                          (228.0, RC + 31.0, 34.0))):
        base = at_angle(deg, rad, 0.0)
        s.proc("stem%d" % k, {"kind": "cylinder", "radius": 1.0, "height": hgt, "radialSegments": 6, "caps": True},
               material=toon("#2fe8d0", ambient=0.62),
               transform={"position": [base[0], hgt * 0.5, base[2]], "rotation": [0, 0, 0], "scale": [1, 1, 1]})
        s.proc("petals%d" % k, {"kind": "sphere", "radius": 6.0, "segments": 8, "rings": 4},
               distribution={"kind": "radial", "count": 6, "radius": 7.2, "plane": "xz", "orientation": "outward"},
               material=toon("#ff6fbf", ambient=0.65, rim=0.25, emissive_col="#ff8fd0"),
               transform={"position": [base[0], hgt, base[2]], "rotation": [0, 15.0 * k, 0], "scale": [1, 1, 1]},
               extra={"sourceTransform": {"scale": [0.75, 0.32, 1.25]}})
        s.proc("bloom%d" % k, {"kind": "sphere", "radius": 4.2, "segments": 8, "rings": 6},
               material=toon("#fff07a", ambient=0.8, emissive=0.5, emissive_col="#fff07a"),
               transform={"position": [base[0], hgt + 0.8, base[2]], "rotation": [0, 0, 0], "scale": [1, 1, 1]})
    d, v = sector(1, 7, RC + 6.0, jitter=(14.0, 0.0, 20.0), seed=91)
    s.proc("jellies", {"kind": "sphere", "radius": 2.4, "segments": 8, "rings": 4}, distribution=d, variation=v,
           material=toon("#ffb0f0", ambient=0.75, rim=0.4, emissive=0.35, emissive_col="#ff8fd0"),
           transform={"position": [0.0, 17.0, 0.0], "rotation": [0, 0, 0], "scale": [1.0, 0.7, 1.0]})
    gem_spin = [{"kind": "twist", "amount": 0.0, "speed": 1.8, "phase": 0.0, "axis": [0.0, 1.0, 0.0],
                 "space": "local"}]
    for a, col in ((1, "#5ff6ff"), (2, "#ff5a3a")):
        d, v = sector(a, 9, RC, jitter=(6.0, 0.0, 0.0), seed=101 + a, margin=16.0)
        s.proc("gems" + AREAS[a][0], {"kind": "sphere", "radius": 1.4, "segments": 4, "rings": 2}, distribution=d,
               variation={"seed": 5, "randomPosition": [6.0, 0.0, 0.0]},
               material=toon(col, ambient=0.75, spec=1.0, emissive=0.3, emissive_col=col), deformers=gem_spin,
               transform={"position": [0.0, 10.0, 0.0], "rotation": [0, 0, 0], "scale": [1.0, 1.5, 1.0]})

    # ---- AREA 3, PIPE DEEP: green pipes either side, orange branch coral, the house-sized shell
    for side, rad in (("In", RC - 26.0), ("Out", RC + 27.0)):
        d, v = sector(2, 6, rad, jitter=(4.0, 0.0, 16.0), seed=111 if side == "In" else 113, margin=10.0)
        v["randomScale"] = [0.0, 0.45, 0.0]
        s.proc("pipe" + side, {"kind": "cylinder", "radius": 3.0, "height": 14.0, "radialSegments": 10,
                               "caps": True}, distribution=d, variation=v, material=toon("#3fd85a", ambient=0.6,
                                                                                          rim=0.2),
               transform={"position": [0.0, 7.0, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})
        s.proc("pipeRim" + side, {"kind": "cylinder", "radius": 3.8, "height": 2.2, "radialSegments": 10,
                                  "caps": True}, distribution=d, variation=v,
               material=toon("#7af07a", ambient=0.7, rim=0.2),
               transform={"position": [0.0, 14.2, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})
    d, v = sector(2, 12, RC + 22.0, jitter=(8.0, 0.0, 26.0), seed=121)
    s.proc("coralC", {"kind": "mesh", "asset": "meshes/bo-coral.glb"}, distribution=d, variation=v,
           material=toon("#ff8a2a", ambient=0.62), transform={"position": [0, 3.0, 0], "rotation": [0, 0, 0],
                                                              "scale": [2.6, 2.6, 2.6]})
    shell_at = at_angle(300.0, RC - 40.0, 0.0)
    pts = []
    for i in range(40):
        u = i / 39.0
        a = 2.0 * math.pi * 3.2 * u
        rr = 9.0 * (1.0 - u) + 0.6
        pts.append({"position": [rr * math.cos(a), 1.5 + 20.0 * u ** 1.1, rr * math.sin(a)]})
    s.proc("shell", {"kind": "tube", "tubeRadius": 5.2, "tubeTaper": 0.08, "tubeSides": 9, "tubeSegments": 160,
                     "tubeTwist": 0.0, "tubeCaps": True,
                     "curve": {"kind": "catmullRom", "generator": "points", "points": pts, "samplesPerSegment": 16,
                               "up": [0.0, 1.0, 0.0]}},
           material=toon("#ffd8b0", ambient=0.68, rim=0.25),
           transform={"position": shell_at, "rotation": [0, 30.0, 0], "scale": [1, 1, 1]})

    # ---- twelve bell flowers per area, the pitch classes, in a row along the lane's inner edge (a xylophone)
    for k in range(12):
        offs = [math.radians(AREAS[a][1] + 52.0 + 2.6 * k) for a in range(3)]
        d = {"kind": "radial", "count": 3, "radius": RC - 11.0, "plane": "xz", "orientation": "outward",
             "startAngle": offs[0] - math.pi / 2.0, "endAngle": offs[0] - math.pi / 2.0 + 2.0 * math.pi}
        hue = mix(hexrgb("#ff5ab4"), hexrgb("#5af0ff"), k / 11.0)
        col = "#%02x%02x%02x" % tuple(int(255 * min(1.0, c ** (1 / 2.2))) for c in hue)
        s.proc("bell%d" % k, {"kind": "sphere", "radius": 1.3, "segments": 6, "rings": 4}, distribution=d,
               material=toon(col, ambient=0.8, rim=0.3, emissive=0.15, emissive_col=col),
               transform={"position": [0.0, 7.5 + 0.35 * k, 0.0], "rotation": [0, 0, 0], "scale": [1.0, 1.25, 1.0]})
        s.proc("bellStem%d" % k, {"kind": "cylinder", "radius": 0.25, "height": 7.0 + 0.35 * k, "radialSegments": 5,
                                  "caps": False}, distribution=d, material=toon("#2fe8a0", ambient=0.7),
               transform={"position": [0.0, (7.0 + 0.35 * k) * 0.5, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]})

    # ---- fish schools circling the ring (tangent-facing fish; their turn is integrated from the mids)
    for name, rad, y, n, col, seed in (("schoolA", RC + 10.0, 13.0, 46, "#ff8a2a", 131),
                                       ("schoolB", RC - 8.0, 18.0, 38, "#ffe066", 133),
                                       ("schoolC", RC + 26.0, 9.0, 30, "#ff6fbf", 137)):
        s.proc(name, {"kind": "mesh", "asset": "meshes/bo-fish.glb"},
               distribution={"kind": "radial", "count": n, "radius": rad, "plane": "xz", "orientation": "tangent"},
               variation={"seed": seed, "randomPosition": [5.0, 4.0, 3.0], "randomUniformScale": 0.3},
               material=toon(col, ambient=0.7, rim=0.3), transform={"position": [0.0, y, 0.0],
                                                                      "rotation": [0, 0, 0], "scale": [1.6, 1.6, 1.6]},
               extra={"sourceTransform": {"rotation": [0.0, 180.0 if name == "schoolB" else 0.0, 0.0]}})
        s.track("procedural/%s/transform/rotation" % name, [
            {"time": 0.0, "value": [0.0, 0.0, 0.0], "interp": "linear"},
            {"time": PERIOD * 0.6, "value": [0.0, 360.0 if name != "schoolB" else -360.0, 0.0], "interp": "linear"}],
            loop=PERIOD * 0.6, mode="add")

    # ---- THE GUIDE: a big friendly voxel fish (29 m) swimming the ring against the swim, outside the lane on the
    # right: the swimmer meets it every 100 s (first alongside at 12 s; 22 degrees ahead at 6 s, the hero still)
    meet = 1.0 / (1.0 / PERIOD + 1.0 / GUIDE_PERIOD)
    th0 = THETA0 + math.radians(GUIDE_AHEAD_AT_6 + 360.0 * 6.0 / meet)
    guide_colours = {"body": ("#ff7a2a", 0.7, 0.3, 0.0), "belly": ("#ffe8b8", 0.8, 0.2, 0.0),
                     "fins": ("#ff4a6a", 0.7, 0.3, 0.0), "eyes": ("#ffffff", 0.95, 0.0, 0.25),
                     "pupils": ("#0a1a4a", 0.6, 0.0, 0.0)}
    for part, (col, amb, rim, em) in guide_colours.items():
        name = "guide" + part.capitalize()
        s.proc(name, {"kind": "mesh", "asset": "meshes/bo-guide-%s.glb" % part},
               distribution={"kind": "radial", "count": 1, "radius": GUIDE_R, "plane": "xz", "orientation": "tangent",
                             "startAngle": th0 - math.pi / 2.0, "endAngle": th0 - math.pi / 2.0},
               material=toon(col, ambient=amb, rim=rim, emissive=em),
               deformers=[{"kind": "bend", "amount": 0.0, "axis": [0.0, 0.0, 1.0], "space": "local"}],
               transform={"position": [0.0, GUIDE_Y, 0.0], "rotation": [0, 0, 0], "scale": [1, 1, 1]},
               extra={"sourceTransform": {"rotation": [0.0, 180.0, 0.0]}})
        s.track("procedural/%s/transform/rotation" % name, [
            {"time": 0.0, "value": [0.0, 0.0, 0.0], "interp": "linear"},
            {"time": GUIDE_PERIOD, "value": [0.0, -360.0, 0.0], "interp": "linear"}], loop=GUIDE_PERIOD, mode="add")

    # ---- bubbles everywhere (rising), a burst round the swimmer (drums, notes), sparkles (highs)
    s.nodes.append({"name": "laneRing", "kind": "spline", "spline": {
        "kind": "catmullRom", "generator": "circle", "closed": True, "count": 64, "radius": RC,
        "center": [0.0, 3.0, 0.0], "axis": [0.0, 1.0, 0.0], "up": [0.0, 0.0, 1.0], "samplesPerSegment": 8}})
    s.particles("bubbles", capacity=9000, seed=3, shape="spline", spline="laneRing", position=[0.0, 0.0, 0.0],
                extent=[16.0, 0.5, 16.0], direction=[0.0, 1.0, 0.0], spawnRate=520.0, lifetimeMin=5.0,
                lifetimeMax=8.0, spread=0.06, speedMin=2.4, speedMax=4.0, gravity=[0, 0, 0], drag=0.0,
                sizeStart=0.55, sizeEnd=0.85, colorStart=hexrgb("#ffffff") + [0.9],
                colorEnd=hexrgb("#bff4ff") + [0.0], emissive=1.6, blend="additive", turbulence=0.5,
                turbulenceScale=0.12)
    s.particles("burst", capacity=4000, seed=7, shape="sphere", position=[0.0, 8.0, 0.0], extent=[6.0, 6.0, 6.0],
                direction=[0.0, 1.0, 0.0], spawnRate=0.0, lifetimeMin=2.0, lifetimeMax=3.5, spread=0.5,
                speedMin=3.0, speedMax=7.0, gravity=[0.0, 2.5, 0.0], drag=0.6, sizeStart=0.35, sizeEnd=0.9,
                colorStart=hexrgb("#ffffff") + [0.9], colorEnd=hexrgb("#bff4ff") + [0.0], emissive=1.8,
                blend="additive", turbulence=0.5, volumeFollow=[1.0, 1.0, 1.0])
    s.particles("sparkle", capacity=3000, seed=11, shape="box", position=[0.0, 9.0, 0.0], extent=[28.0, 10.0, 28.0],
                direction=[0.0, 1.0, 0.0], spawnRate=30.0, lifetimeMin=0.25, lifetimeMax=0.6, spread=1.0,
                speedMin=0.2, speedMax=0.8, gravity=[0, 0, 0], drag=0.0, sizeStart=0.16, sizeEnd=0.0,
                colorStart=hexrgb("#fff7c0") + [1.0], colorEnd=hexrgb("#7ff6ff") + [0.0], emissive=8.0,
                blend="additive", volumeFollow=[1.0, 1.0, 1.0])

    # ---- light shafts from the surface (the Effect Library's light beams)
    for k in range(6):
        p = at_angle(30.0 + 60.0 * k, RC + (14.0 if k % 2 else -12.0), 70.0)
        s.beam("shaft%d" % k, p, tilt=12.0, yaw=30.0 + 60.0 * k, color=(0.75, 0.95, 1.0), intensity=0.5,
               length=80.0, angle=7.0)

    camera_track(s)
    s.params_({"camera/lens/focalLength": 22.0, "post/bloom/intensity": 0.32, "post/bloom/threshold": 1.0,
               "post/bloom/emissionWeight": 1.0, "post/output/vignette": 0.35, "post/output/grain": 0.008,
               "post/shock/width": 0.1, "post/shock/chroma": 0.15,
               # a deep-navy line round every shape: the strong silhouette of a game sprite, kept thin
               "post/outline/amount": 1.0, "post/outline/color": hexrgb("#081a52"), "post/outline/intensity": 1.0,
               "post/outline/width": 1.6, "post/outline/depthThreshold": 0.08, "post/outline/normalThreshold": 0.5,
               "post/outline/objectEdges": 1.0})
    instrument(s)
    s.region("lane", box=[0.25, 0.3, 0.75, 0.8])
    return s
