"""7. CHROMATIC TOPOGRAPHY: CONTOUR VALLEY (05-brief-direction-correction.md; ABSTRACT-PLAN.md section 7).

A landscape as a sculptural colour field, flown through. The camera skims low along a winding valley, over a glowing
turquoise river, between enormous smooth hills whose colour is their HEIGHT: hard hypsometric bands from violet on the
valley floor through magenta, coral and orange to gold on the crests, ruled with fine contour lines that flow up the
slopes with the music. Teal cone trees and cobalt round trees stand in groves on the slopes; cyan crystals grow on the
ridges; far off, the land rises into gold walls under a cream and cobalt sky.

Grammar: SMOOTH FORM + COLOUR BY HEIGHT. The land is one smooth-shaded heightfield (a sculpted valley, rounded hills,
ridged crests; generated by tools/sonic_vfx/meshes.py, periodic along the flight so three copies and a sawtooth make an
endless valley), coloured by a material program: its height quantised into six bands, a soft light from the left, contour
lines every 22 m, the river's glow where the land meets the floor, distance haze. Everything else is baked from the same
height function, so the trees stand on the slopes and the crystals on the crests.

Distinct from Digital Alpine (faceted, restrained, reflective): this one is smooth, saturated, graphic, map-like.
"""
import math
import os

from .. import kit
from .. import meshes as mx
from ..kit import R, M, hexrgb, mix, scale3, SLOW, MEDIUM, FAST, HIT, VERY_SLOW

ID = "chromatic-topography"
TITLE = "Chromatic Topography"

# ---- the palette: warm land by height, a cool river and sky
# seven bands by height, two ramps meeting at magenta: indigo, violet, (magenta), coral, orange, gold, cream
BANDS = ["#1d2a72", "#5a2a92", "#b0308c", "#ec4f66", "#f68f4c", "#fbd36a", "#fff3cf"]
RIVER = "#39f2dc"
TREE_CONE = "#0d5f73"
TREE_BALL = "#2346b8"
CRYSTAL = "#9ff6ff"
SKY_HORIZON = "#ffe3c6"
SKY_MID = "#86d4ea"
SKY_ZENITH = "#2448a8"
HAZE = "#f6d9c6"

LZ = 2400.0               # the valley's period along the flight (metres)
PERIOD = 120.0            # seconds per period: 20 m/s
COPIES = 3
WIDTH = 1500.0            # half-width of the land
Y_TOP = 520.0             # the top of the colour ramp
CONTOUR = 22.0            # metres between contour lines
CAM_UP = 64.0             # the glide's height over the river

MESH_DIR = os.path.join(kit.ABSTRACT_DIR, "meshes")
LIGHT = (-0.55, 0.62, 0.25)
HERO_AT = 50.0            # the hero still: high over the hills, the river winding away


def unit(v):
    n = math.sqrt(sum(x * x for x in v))
    return tuple(x / n for x in v)


L = unit(LIGHT)

DESIGN = {
    "category": "chromatic landscape",
    "thesis": "Contour Valley: a landscape as a sculptural colour field. You skim a glowing river down a winding valley "
              "between smooth hills coloured by their height in hard bands, ruled with contour lines that flow up the "
              "slopes with the music; the river rises and brightens with the bass.",
    "composition": {
        "background": "the valley's far bends and gold walls dissolving into a cream horizon under a cobalt sky",
        "midground": "enormous banded hills, groves of cone trees, crystals on the crests",
        "foreground": "the turquoise river under the camera, the valley's walls sweeping past",
        "focal": "the river's next bend",
        "secondary": ["the contour lines", "the groves", "the crystals"],
        "atmosphere": "cream haze with distance",
        "post": "a soft bloom on the river and the crystals",
        "camera": "a low glide along the river, banking through the bends",
    },
    "palette": {"dominant": BANDS[3], "secondary": BANDS[1], "accent": RIVER, "highlight": BANDS[5],
                "background_value": "light (a cream horizon)",
                "saturation": "saturated warm bands; turquoise and cobalt accents"},
    "motion": {
        "very_slow": ["the land rising as a piece builds", "the palette drifting"],
        "medium": ["the glide", "the contour lines flowing up the slopes"],
        "fast": ["groves swaying", "crystals lighting on notes"],
        "extremely_fast": ["a band of light running out across the land", "pollen sparks"],
    },
    "vocabulary": [
        ["bass", "response.bass", "the river rises up its banks and brightens"],
        ["kick", "response.kick", "a band of light runs out across the land from the camera"],
        ["snare", "response.snare", "the groves bloom (their colours flare)"],
        ["mids", "audio.mid", "the contour lines flow up the slopes"],
        ["low mids", "audio.lowMid", "the round trees glow"],
        ["highs", "audio.treble", "pollen sparks over the river; the contour lines brighten"],
        ["beat", "beat.pulse", "the contour lines pulse"],
        ["brightness", "sonic.brightness.slow", "the whole palette drifts (hue) and the haze warms"],
        ["intensity", "response.intensity", "STRUCTURE: the land rises (the hills grow taller as the piece builds)"],
        ["level", "response.level", "the land breathes (a slow swell rolls through it)"],
        ["pitch class", "notes.class.0", "twelve families of crystals, one per pitch class, light on their crests"],
        ["chord", "notes.polyphony", "the river's glow widens with the chord"],
        ["velocity", "notes.lastVelocity", "how bright a crystal flares"],
        ["mod wheel", "control.modwheel", "STRUCTURE: the contour spacing (fine survey lines to broad terraces)"],
        ["silence", "(no input)", "the glide goes on down the valley"],
    ],
    "tier": "light: one smooth heightfield (three copies), baked groves and crystals, four unlit programs, no lights",
}


# ================================================================================================ the land
def path_x(z):
    """The valley's (and the river's) centre line: periodic in z with period LZ."""
    s = 2.0 * math.pi * z / LZ
    return 170.0 * math.sin(s) + 75.0 * math.sin(3.0 * s + 1.1) + 28.0 * math.sin(5.0 * s + 0.4)


def height(x, z):
    d = abs(x - path_x(z))
    bank = mx.smooth(12.0, 330.0, d)
    y = 120.0 * bank ** 1.25
    hills = mx.fbm_p(x / 480.0, z / 480.0, 5, 3, py=int(LZ / 480.0))
    crests = mx.fbm_p(x / 300.0, z / 300.0, 9, 3, py=int(LZ / 300.0), ridged=True)
    y += (380.0 * hills + 140.0 * crests - 140.0) * mx.smooth(50.0, 420.0, d)
    y += 90.0 * mx.smooth(700.0, 1400.0, d)           # the country rises a little away from the valley
    return max(y, -1.0) if d > 14.0 else -1.0


def generate_meshes():
    """The land, the river, the groves and the crystals for one period (z from -LZ to 0). Deterministic."""
    v, n, i = mx.heightfield(-WIDTH, WIDTH, -LZ, 0.0, 132, 220, height)
    mx.write_indexed(os.path.join(MESH_DIR, "ct-land.glb"), v, n, i, "land")
    v, n, i = mx.ribbon(path_x, 20.0, lambda z: 0.0, -LZ, 0.0, 240, lift=0.3)
    mx.write_indexed(os.path.join(MESH_DIR, "ct-river.glb"), v, n, i, "river")
    cones, balls = [], []
    crystals = [[] for _ in range(12)]
    k = 0
    for j in range(5200):
        u, w = mx._hash(j, 1, 77), mx._hash(j, 2, 77)
        z = -LZ * u
        x = path_x(z) + (w - 0.5) * 2.0 * 900.0
        d = abs(x - path_x(z))
        if d < 40.0:
            continue
        y = height(x, z)
        # groves: clustered by a noise mask, on the lower and middle slopes
        grove = mx.fbm_p(x / 160.0, z / 160.0, 21, 2, py=int(LZ / 160.0))
        if 6.0 < y < 300.0 and grove > 0.56 and mx._hash(j, 3, 77) < 0.55:
            sc = 0.7 + 0.6 * mx._hash(j, 4, 77)
            if mx._hash(j, 5, 77) < 0.62:
                cones += mx.cone((x, y - 1.0, z), 7.0 * sc, 26.0 * sc, 6, seed=j)
            else:
                r = 7.5 * sc
                balls += mx.ball((x, y + 7.0 * sc + r * 0.8, z), r, 7, 5)
                balls += mx.prism((x, y - 1.0, z), 0.9 * sc, 8.0 * sc + r * 0.3, 4, 0.0, seed=j)
        # crystals on the crests: high and ridged, in twelve families (the pitch classes)
        elif y > 330.0 and mx._hash(j, 6, 77) < 0.08:
            fam = k % 12
            k += 1
            for c in range(3 + int(3 * mx._hash(j, 7, 77))):
                ox, oz = (mx._hash(j, 8 + c, 77) - 0.5) * 18.0, (mx._hash(j, 20 + c, 77) - 0.5) * 18.0
                hgt = 18.0 + 30.0 * mx._hash(j, 30 + c, 77)
                crystals[fam] += mx.prism((x + ox, height(x + ox, z + oz) - 2.0, z + oz), 3.0 + 2.5 *
                                          mx._hash(j, 40 + c, 77), hgt, 6, 0.32, seed=j * 7 + c,
                                          lean=((mx._hash(j, 50 + c, 77) - 0.5) * 0.5,
                                                (mx._hash(j, 60 + c, 77) - 0.5) * 0.5))
    mx.write_faceted(os.path.join(MESH_DIR, "ct-cones.glb"), cones, "cones")
    mx.write_faceted(os.path.join(MESH_DIR, "ct-balls.glb"), balls, "balls")
    for fam in range(12):
        tris = crystals[fam] or mx.prism((0.0, -50.0, 0.0), 0.1, 0.1, 3)   # never empty
        mx.write_faceted(os.path.join(MESH_DIR, "ct-crystal%d.glb" % fam), tris, "crystal%d" % fam)


# ================================================================================================ programs
HZ0, HZ1, HZ_CURVE = 20.0, 260.0, 0.75    # haze, decametres (a material op's constants are clamped to +-1000)
GLOW_H = 1.6                              # the river's glow up the banks (metres)
BAND_REST = -900.0                        # the light band parked far off (decametres)
BAND_W = 9.0


def land_program():
    """The land, unlit. Ops (1-based): 7 the height's ramp (y0, y1), 8-18 the seven bands (thresholds), 20/22 the
    low and high colour ramps, 25 the light, 27 the contour lines (palette: value = their phase, constant3 =
    1/spacing), 30 the lines' tint, 33 the river's glow height, 34 its colour, 39 the haze colour, 40 minus the light
    band's distance, 44 the band's colour."""
    return {
        "name": "ctLand",
        "ops": [
            {"kind": "input", "dst": 0, "input": "worldPosition"},                                     # 1
            {"kind": "input", "dst": 1, "input": "normal"},                                            # 2
            {"kind": "input", "dst": 2, "input": "cameraDistance"},                                    # 3
            {"kind": "constant", "dst": 3, "constant": [0.1, 0.1, 0.1, 0.1]},                          # 4
            {"kind": "multiply", "dst": 2, "srcA": 2, "srcB": 3},                                      # 5 decametres
            {"kind": "swizzle", "dst": 3, "srcA": 0, "constant": [1.0, 1.0, 1.0, 1.0]},               # 6 y
            {"kind": "remap", "dst": 4, "srcA": 3, "value": 1.0, "constant": [0.0, Y_TOP, 0.0, 1.0]},  # 7 t
            {"kind": "threshold", "dst": 5, "srcA": 4, "value": 0.07},                                 # 8
            {"kind": "threshold", "dst": 6, "srcA": 4, "value": 0.17},                                 # 9
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 10
            {"kind": "threshold", "dst": 6, "srcA": 4, "value": 0.3},                                  # 11
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 12
            {"kind": "threshold", "dst": 6, "srcA": 4, "value": 0.45},                                 # 13
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 14
            {"kind": "threshold", "dst": 6, "srcA": 4, "value": 0.62},                                 # 15
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 16
            {"kind": "threshold", "dst": 6, "srcA": 4, "value": 0.8},                                  # 17
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 18 band 0..6
            {"kind": "remap", "dst": 6, "srcA": 5, "value": 1.0, "constant": [0.0, 3.0, 0.0, 1.0]},    # 19 low half
            {"kind": "ramp", "dst": 6, "srcA": 6, "constant": hexrgb(BANDS[0]) + [1.0],
             "constant2": hexrgb(BANDS[1]) + [1.0], "constant3": hexrgb(BANDS[2]) + [1.0]},            # 20 low ramp
            {"kind": "remap", "dst": 7, "srcA": 5, "value": 1.0, "constant": [3.0, 6.0, 0.0, 1.0]},    # 21 high half
            {"kind": "ramp", "dst": 7, "srcA": 7, "constant": hexrgb(BANDS[2]) + [1.0],
             "constant2": hexrgb(BANDS[4]) + [1.0], "constant3": hexrgb(BANDS[6]) + [1.0]},            # 22 high ramp
            {"kind": "threshold", "dst": 5, "srcA": 5, "value": 3.0},                                  # 23
            {"kind": "mixBy", "dst": 5, "srcA": 6, "srcB": 7, "srcC": 5},                              # 24 colour
            {"kind": "gradient", "dst": 6, "srcA": 1, "constant": list(L) + [0.62], "value": 0.45},    # 25 light
            {"kind": "multiply", "dst": 5, "srcA": 5, "srcB": 6},                                      # 26
            {"kind": "palette", "dst": 6, "srcA": 3, "value": 0.0, "constant": [0.5, 0.5, 0.5, 0.5],
             "constant2": [0.5, 0.5, 0.5, 0.5], "constant3": [1.0 / CONTOUR] * 4,
             "constant4": [0.0, 0.0, 0.0, 0.0]},                                                        # 27 lines
            {"kind": "smoothstep", "dst": 6, "srcA": 6, "constant": [0.93, 0.995, 0.0, 0.0]},          # 28
            {"kind": "swizzle", "dst": 6, "srcA": 6, "constant": [0.0, 0.0, 0.0, 0.0]},               # 29
            {"kind": "constant", "dst": 7, "constant": [0.58, 0.5, 0.66, 1.0]},                        # 30
            {"kind": "multiply", "dst": 7, "srcA": 5, "srcB": 7},                                      # 31 line tint
            {"kind": "mixBy", "dst": 5, "srcA": 5, "srcB": 7, "srcC": 6},                              # 32 (lines)
            {"kind": "smoothstep", "dst": 6, "srcA": 3, "constant": [GLOW_H, -0.5, 0.0, 0.0]},         # 33 river glow
            {"kind": "constant", "dst": 7, "constant": hexrgb(RIVER, 0.8) + [1.0]},                    # 34
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 7},                                      # 35
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 36
            {"kind": "smoothstep", "dst": 6, "srcA": 2, "constant": [HZ0, HZ1, 0.0, 0.0]},             # 37 haze
            {"kind": "power", "dst": 6, "srcA": 6, "value": HZ_CURVE},                                 # 38
            {"kind": "constant", "dst": 7, "constant": hexrgb(HAZE) + [1.0]},                          # 39
            {"kind": "constant", "dst": 4, "constant": [BAND_REST] * 4},                              # 40 -band dist.
            {"kind": "mixBy", "dst": 5, "srcA": 5, "srcB": 7, "srcC": 6},                              # 41 hazed
            {"kind": "add", "dst": 6, "srcA": 2, "srcB": 4},                                           # 42
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 6},                                      # 43
            {"kind": "constant", "dst": 7, "constant": hexrgb("#fff2d0", 0.7) + [1.0]},                # 44 band
            {"kind": "gradient", "dst": 6, "srcA": 6, "constant": [1.0, 0.0, 0.0, 1.0],
             "value": -1.0 / (BAND_W * BAND_W)},                                                        # 45
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 7},                                      # 46
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 47
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 5, "emissionIntensity": 1.0, "opacity": -1,
    }


def flat_program(name):
    """Trees and crystals, unlit: the material's own emission (its colour x intensity) as the colour, lit softly from
    the left, hazed with distance."""
    return {
        "name": name,
        "ops": [
            {"kind": "input", "dst": 0, "input": "materialEmission"},                                  # 1
            {"kind": "input", "dst": 1, "input": "normal"},                                            # 2
            {"kind": "gradient", "dst": 2, "srcA": 1, "constant": list(L) + [0.45], "value": 0.7},     # 3
            {"kind": "multiply", "dst": 0, "srcA": 0, "srcB": 2},                                      # 4
            {"kind": "input", "dst": 3, "input": "cameraDistance"},                                    # 5
            {"kind": "constant", "dst": 4, "constant": [0.1, 0.1, 0.1, 0.1]},                          # 6
            {"kind": "multiply", "dst": 3, "srcA": 3, "srcB": 4},                                      # 7
            {"kind": "smoothstep", "dst": 3, "srcA": 3, "constant": [HZ0, HZ1, 0.0, 0.0]},             # 8
            {"kind": "power", "dst": 3, "srcA": 3, "value": HZ_CURVE},                                 # 9
            {"kind": "constant", "dst": 4, "constant": hexrgb(HAZE) + [1.0]},                          # 10
            {"kind": "mixBy", "dst": 0, "srcA": 0, "srcB": 4, "srcC": 3},                              # 11
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 0, "emissionIntensity": 1.0, "opacity": -1,
    }


def river_program():
    """The river: turquoise light flowing towards the camera (bands of brightness along z, moving with time), hazed.
    Ops: 4 the flow's speed (the time's multiplier), 7 the bands' frequency, 9 the colour."""
    return {
        "name": "ctRiver",
        "ops": [
            {"kind": "input", "dst": 0, "input": "worldPosition"},                                     # 1
            {"kind": "swizzle", "dst": 0, "srcA": 0, "constant": [2.0, 2.0, 2.0, 2.0]},               # 2 z
            {"kind": "input", "dst": 1, "input": "time"},                                              # 3
            {"kind": "constant", "dst": 2, "constant": [-12.0, -12.0, -12.0, -12.0]},                  # 4 flow
            {"kind": "multiply", "dst": 1, "srcA": 1, "srcB": 2},                                      # 5
            {"kind": "add", "dst": 0, "srcA": 0, "srcB": 1},                                           # 6
            {"kind": "palette", "dst": 0, "srcA": 0, "value": 0.0, "constant": [0.62, 0.62, 0.62, 0.62],
             "constant2": [0.38, 0.38, 0.38, 0.38], "constant3": [1.0 / 38.0] * 4,
             "constant4": [0.0, 0.0, 0.0, 0.0]},                                                        # 7
            {"kind": "swizzle", "dst": 0, "srcA": 0, "constant": [0.0, 0.0, 0.0, 0.0]},               # 8
            {"kind": "constant", "dst": 1, "constant": hexrgb(RIVER, 2.4) + [1.0]},                    # 9
            {"kind": "multiply", "dst": 0, "srcA": 0, "srcB": 1},                                      # 10
            {"kind": "input", "dst": 3, "input": "cameraDistance"},                                    # 11
            {"kind": "constant", "dst": 4, "constant": [0.1, 0.1, 0.1, 0.1]},                          # 12
            {"kind": "multiply", "dst": 3, "srcA": 3, "srcB": 4},                                      # 13
            {"kind": "smoothstep", "dst": 3, "srcA": 3, "constant": [HZ0, HZ1, 0.0, 0.0]},             # 14
            {"kind": "constant", "dst": 4, "constant": hexrgb(HAZE) + [1.0]},                          # 15
            {"kind": "mixBy", "dst": 0, "srcA": 0, "srcB": 4, "srcC": 3},                              # 16
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 0, "emissionIntensity": 1.0, "opacity": -1,
    }


def sky_program():
    """The dome: cream at the horizon, sky cyan, cobalt at the zenith (by the view's elevation)."""
    return {
        "name": "ctSky",
        "ops": [
            {"kind": "input", "dst": 0, "input": "viewDirection"},                                     # 1
            {"kind": "swizzle", "dst": 1, "srcA": 0, "constant": [1.0, 1.0, 1.0, 1.0]},               # 2 v.y
            {"kind": "remap", "dst": 1, "srcA": 1, "value": 1.0, "constant": [0.0, -0.6, 0.0, 1.0]},   # 3 elevation
            {"kind": "power", "dst": 1, "srcA": 1, "value": 0.6},                                      # 4
            {"kind": "ramp", "dst": 2, "srcA": 1, "constant": hexrgb(SKY_HORIZON) + [1.0],
             "constant2": hexrgb(SKY_MID) + [1.0], "constant3": hexrgb(SKY_ZENITH) + [1.0]},           # 5
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 2, "emissionIntensity": 1.0, "opacity": -1,
    }


def unlit(hexc, intensity, program, double=False):
    m = {"baseColor": [0.0, 0.0, 0.0], "emissiveColor": hexrgb(hexc), "emissiveIntensity": float(intensity),
         "roughness": 1.0, "metallic": 0.0, "unlit": True, "program": program}
    if double:
        m["doubleSided"] = True
    return m


def copies():
    return {"kind": "linear", "count": COPIES, "start": [0.0, 0.0, -(COPIES - 1) * LZ], "end": [0.0, 0.0, 0.0]}


TRAVELLING = ["land", "river", "cones", "balls"] + ["crystal%d" % k for k in range(12)]


def instrument(s):
    """The modulation map (ABSTRACT-PLAN.md section 7)."""
    P = "procedural/%s/"
    # ---- BASS: the river rises up its banks (the glow's height, op 33) and brightens (op 34)
    s.route(R("bass", "material/ctLand/op/33/smoothstep/constant", 5.0, comp=0, attackMs=40, decayMs=500),
            R("bass", "material/ctLand/op/34/constant/constant", 0.35, attackMs=30, decayMs=500),
            R("bass", "material/ctRiver/op/9/constant/constant", 1.2, attackMs=30, decayMs=400))
    # ---- KICK: a band of light runs out across the land (op 40: minus its distance, decametres)
    s.route(R("kick", "material/ctLand/op/40/constant/constant", -BAND_REST, threshold="binary", thresholdLevel=0.3,
              envelope="linearfall", envelopeHoldMs=0, envelopeFallPerSecond=0.9))
    # ---- SNARE: the groves bloom (their colour flares); LOW MIDS: the round trees glow
    s.route(R("snare", P % "cones" + "material/emissive", 1.4, attackMs=0, decayMs=320),
            R("snare", P % "balls" + "material/emissive", 1.4, attackMs=0, decayMs=320),
            R("audio.lowMid", P % "balls" + "material/emissive", 0.8, attackMs=120, decayMs=700))
    # ---- MIDS: the contour lines flow up the slopes (the palette's phase, integrated)
    s.route(R("audio.mid", "material/ctLand/op/27/palette/value", 30.0, integrate=True, attackMs=80, decayMs=600))
    # ---- HIGHS: pollen sparks over the river; the contour lines brighten (their tint towards white); BEAT pulses them
    s.route(R("audio.treble", "particles/pollen/spawnRate", 700.0, attackMs=20, decayMs=250),
            R("audio.treble", "material/ctLand/op/30/constant/constant", 0.9, attackMs=30, decayMs=300),
            R("beat", "material/ctLand/op/30/constant/constant", 0.35, attackMs=0, decayMs=160))
    # ---- CENTROID: the palette drifts and the haze warms, very slowly
    s.route(R("brightnessSlow", "post/grade/hueShift", 0.6, offset=-0.4, **VERY_SLOW),
            R("brightnessSlow", "material/ctLand/op/39/constant/constant", 0.12, comp=0, **SLOW))
    # ---- INTENSITY: STRUCTURE -- the land rises as the piece builds
    for node in ("land", "cones", "balls") + tuple("crystal%d" % k for k in range(12)):
        s.route(R("intensity", P % node + "transform/scale", 0.3, comp=1, **VERY_SLOW))
    # ---- LEVEL: the land breathes (a slow swell rolls through it, metres), and all that stands on it with it
    for node in ("land", "cones", "balls") + tuple("crystal%d" % k for k in range(12)):
        s.route(R("level", P % node + "deform/1/amount", 14.0, attackMs=300, decayMs=1500))
    # ---- MIDI: twelve families of crystals, the pitch classes; velocity is how bright; the chord widens the river
    for k in range(12):
        s.route(R("notes.class.%d" % k, P % ("crystal%d" % k) + "material/emissive", 3.2, depth="lastVelocity",
                  attackMs=0, decayMs=900))
    s.route(R("polyphony", "material/ctLand/op/33/smoothstep/constant", 9.0, comp=0, **MEDIUM))
    # ---- MOD WHEEL: STRUCTURE -- the contour spacing, from fine survey lines to broad terraces
    wheel = s.modwheel()
    s.route(R(wheel, "material/ctLand/op/27/palette/constant3", -1.0 / CONTOUR * 0.7, attackMs=200, decayMs=200))


def camera_track(s):
    """The glide: the world slides towards the camera (the sawtooth), and the camera steers to keep over the river,
    looking at the next bend and banking into it."""
    kp, kt, kr = [], [], []
    steps = 120
    v = LZ / PERIOD
    for i in range(steps + 1):
        t = PERIOD * i / steps
        z_local = -v * t                          # the land under the camera, in the land's own coordinates
        x = path_x(z_local)
        ahead = 420.0
        xa = path_x(z_local - ahead)
        xb = path_x(z_local - ahead * 0.5)
        up = CAM_UP + 270.0 * (0.5 - 0.5 * math.cos(2.0 * math.pi * t / PERIOD)) ** 1.6   # up over the hills
        pos = (x, up, 0.0)
        tgt = (xa * 0.6 + xb * 0.4, up * 0.3, -ahead)
        # bank into the bend: the path's curvature ahead
        curv = (path_x(z_local - 60.0) - 2.0 * x + path_x(z_local + 60.0)) / 3600.0
        kp.append({"time": round(t, 4), "value": [round(c, 3) for c in pos], "interp": "smooth"})
        kt.append({"time": round(t, 4), "value": [round(c, 3) for c in tgt], "interp": "smooth"})
        kr.append({"time": round(t, 4), "value": round(max(-9.0, min(9.0, -curv * 2600.0)), 3), "interp": "smooth"})
    s.track("camera/position", kp, loop=PERIOD)
    s.track("camera/target", kt, loop=PERIOD)
    s.track("camera/roll", kr, loop=PERIOD)
    s.camera = {"mode": 1, "position": kp[0]["value"], "target": kt[0]["value"], "fov": 50.0, "orbitSpeed": 0.0}


def build():
    generate_meshes()
    s = kit.Scene(ID, TITLE, DESIGN)
    s.response = {"sensitivity": 0.5, "transient": 0.55, "sustain": 0.55, "attack": 1.0, "release": 1.1,
                  "floorDb": -44.0, "rangeDb": 42.0}     # mastered music does not saturate the levels
    s.environment = {
        "intensity": 0.0, "background": hexrgb(SKY_HORIZON), "fogColor": hexrgb(HAZE), "volumeDensity": 0.0,
        "skyIntensity": 1.0,
        "sky": {"enabled": True, "zenithColor": hexrgb(SKY_ZENITH), "horizonColor": hexrgb(SKY_HORIZON),
                "groundColor": hexrgb(SKY_HORIZON), "haze": 0.3, "sunIntensity": 0.0, "intensity": 1.0,
                "background": True, "useKeyLight": False},
    }
    for prog in (land_program(), flat_program("ctFlat"), river_program(), sky_program()):
        s.program(prog)

    s.proc("dome", {"kind": "sphere", "radius": 1000.0, "segments": 64, "rings": 32},
           material=unlit("#000000", 0.0, "ctSky", double=True),
           transform={"position": [0.0, 0.0, 0.0], "rotation": [0.0, 0.0, 0.0], "scale": [6.0, 6.0, 6.0]})

    # the land breathes: a slow swell rolling outward from the camera (a sine train, 700 m long, at 90 m/s)
    s.nodes.append({"name": "swell", "kind": "field", "field": {
        "kind": "wave", "waveGeometry": "cylindrical", "waveShape": "sine", "amplitude": 1.0, "wavelength": 700.0,
        "waveSpeed": 90.0, "waveWidth": 0.0, "axis": [0.0, 1.0, 0.0], "position": [0.0, 0.0, 0.0], "strength": 1.0}})
    swell = [{"kind": "field", "field": "swell", "amount": 0.0, "axis": [0.0, 1.0, 0.0], "space": "world",
              "alongNormal": False}]

    s.proc("land", {"kind": "mesh", "asset": "meshes/ct-land.glb"}, distribution=copies(),
           material=unlit("#000000", 0.0, "ctLand"), deformers=swell)
    s.proc("river", {"kind": "mesh", "asset": "meshes/ct-river.glb"}, distribution=copies(),
           material=unlit(RIVER, 1.0, "ctRiver"))
    s.proc("cones", {"kind": "mesh", "asset": "meshes/ct-cones.glb"}, distribution=copies(),
           material=unlit(TREE_CONE, 1.0, "ctFlat"), deformers=swell)
    s.proc("balls", {"kind": "mesh", "asset": "meshes/ct-balls.glb"}, distribution=copies(),
           material=unlit(TREE_BALL, 1.0, "ctFlat"), deformers=swell)
    for k in range(12):
        s.proc("crystal%d" % k, {"kind": "mesh", "asset": "meshes/ct-crystal%d.glb" % k}, distribution=copies(),
               material=unlit(CRYSTAL, 0.55, "ctFlat"), deformers=swell)

    # the flight: every travelling part slides one period towards the camera, then back (seamless: the land is periodic)
    for node in TRAVELLING:
        s.track("procedural/%s/transform/position" % node, [
            {"time": 0.0, "value": [0.0, 0.0, 0.0], "interp": "linear"},
            {"time": PERIOD, "value": [0.0, 0.0, LZ], "interp": "linear"}], loop=PERIOD)

    # pollen sparks over the river (the highs), drifting with the land
    s.particles("pollen", capacity=5000, seed=13, shape="box", position=[0.0, 30.0, -260.0],
                extent=[220.0, 26.0, 240.0], direction=[0.0, 0.0, 1.0], spawnRate=40.0, lifetimeMin=2.0,
                lifetimeMax=4.0, spread=0.05, speedMin=20.0, speedMax=20.0, gravity=[0, 0, 0], drag=0.0,
                sizeStart=0.35, sizeEnd=0.0, colorStart=hexrgb("#fffbe0") + [1.0], colorEnd=hexrgb(RIVER) + [0.0],
                emissive=6.0, blend="additive", turbulence=0.6, turbulenceScale=0.05)

    camera_track(s)
    s.params_({"camera/lens/focalLength": 22.0, "post/bloom/intensity": 0.35, "post/bloom/threshold": 1.1,
               "post/bloom/emissionWeight": 1.0, "post/output/vignette": 0.32, "post/output/grain": 0.01,
               "post/tonemap/operator": 4})
    instrument(s)
    s.region("valley", box=[0.25, 0.35, 0.75, 0.8])
    s.region("sky", box=[0.0, 0.0, 1.0, 0.3])
    return s
