"""6. DIGITAL ALPINE: GLASS CALDERA (07-brief-digital-alpine.md; ABSTRACT-PLAN.md section 6).

A digital painting of mountains round a mirror lake, flown through. The camera glides low round a caldera lake, banking
gently, the island peak always on its inside; round the lake stand four ranges of faceted mountains, each farther,
higher and paler, separated by arms of water, dissolving into a rose and violet sky; the water doubles everything.

Grammar: the land is FACETS. Each range is a ring of irregular flat triangles (a jittered polar grid, ridged noise for
the crests, generated by tools/sonic_vfx/meshes.py into examples/sonic-abstract/meshes/), a few thousand triangles in
all. No textures, no lines, no outlines: the facets are coloured by a painter's rule (a material program, unlit): warm
where they face the low sun, lilac where they face the sky, indigo in shadow, and with distance
the colour of the sky behind them (warm towards the sun, cool away from it), so each range is paler than the one before.

The water is not a surface. Every landform has a TWIN, its mirror image below the waterline (a mirrored mesh), drawn
darker and bluer by the same program; the sky is a dome whose program paints the sky above the horizon and its mirror
image below it, with the low sun's path broken by ripples at the point where each view ray meets the water. So the lake
reflects the mountains and the sky exactly, for nothing.

The signature, AUDIO TOPOGRAPHY: a travelling wave field rolls outward from the island through the ranges (a
world-space field deformer on every landform and, mirrored, on every twin), as tall as the music is strong; onsets drop
rings of light on the water and send a band of light out through the ranges.
"""
import math
import os

from .. import kit
from .. import meshes as mx
from ..kit import R, M, hexrgb, mix, scale3, SLOW, MEDIUM, FAST, HIT, VERY_SLOW

ID = "digital-alpine"
TITLE = "Digital Alpine"

# ---- the palette (blue and violet, a peach sun)
ZENITH = "#0e1840"
VIOLET = "#4d4386"
HORIZON_WARM = "#f4c0a0"
HORIZON_COOL = "#a985b4"
SUN = "#fff1dc"
GLOW = "#ff9e72"
SHADOW = "#160f38"
SKYLIT = "#2f2a6e"
SUNLIT = "#e0785e"
HAZE_WARM = "#e3b3a6"
HAZE_COOL = "#a587b6"
WATER = (0.36, 0.45, 0.86)      # what the lake keeps of what it reflects (darker, bluer)

SUN_DIR = (0.62, 0.17, -0.776)   # towards the sun: low (9.7 degrees), fixed in the world
CAM_R = 320.0                    # the flight circle's radius round the island
CAM_H = 9.0
PERIOD = 170.0                   # one circuit of the lake
THETA0 = 0.3                     # where the circuit starts (radians): at 6 s the low sun is 13 degrees left of centre

MESH_DIR = os.path.join(kit.ABSTRACT_DIR, "meshes")


def norm(v):
    n = math.sqrt(sum(x * x for x in v))
    return tuple(x / n for x in v)


S = norm(SUN_DIR)
SH = norm((S[0], 0.0, S[2]))

DESIGN = {
    "category": "digital landscape",
    "thesis": "Glass Caldera: a digital painting of faceted mountains round a mirror lake, flown through at dusk. The "
              "music raises slow waves of topography that roll out from the island through every range; onsets drop "
              "rings of light on the water and send light out through the ranges.",
    "composition": {
        "background": "the far ranges dissolving into a rose and violet sky",
        "midground": "the main range of faceted peaks, their twins in the lake",
        "foreground": "glassy water, rocks sliding past, the island on the inside of the turn",
        "focal": "the low sun and its broken path on the water",
        "secondary": ["the island peak", "the lanterns on the shore", "the rings of light on the water"],
        "atmosphere": "distance haze painted per facet in the sky's own colour",
        "post": "a little bloom on the sun only",
        "camera": "a low glide round the lake, banking into the turn",
    },
    "palette": {"dominant": SHADOW, "secondary": VIOLET, "accent": GLOW, "highlight": SUN,
                "background_value": "mid (a rose horizon under deep blue)",
                "saturation": "restrained: one warm light, everything else violet and blue"},
    "motion": {
        "very_slow": ["the circuit of the lake", "the ranges rising with a build"],
        "medium": ["the topography waves rolling out", "ripples drifting"],
        "fast": ["lanterns answering notes"],
        "extremely_fast": ["glints on the water", "a ring of light where an onset lands"],
    },
    "vocabulary": [
        ["bass", "response.bass", "the shore range lights from within; the sun's path on the water brightens"],
        ["low mids", "audio.lowMid", "the main range lights"],
        ["mids", "audio.mid", "the far range lights; the water's ripples deepen"],
        ["high mids", "audio.highMid", "the distant range lights"],
        ["highs", "audio.treble", "glints scatter on the water; the sun's glow brightens"],
        ["level", "response.level", "AUDIO TOPOGRAPHY: the waves rolling out through the mountains grow taller"],
        ["kick", "response.kick", "the low sun flares across every facet that faces it; rings of light land on the "
         "water"],
        ["snare", "response.snare", "a flash along the horizon"],
        ["brightness", "sonic.brightness.slow", "the whole palette drifts warmer or cooler"],
        ["intensity", "response.intensity", "STRUCTURE: the ranges rise as the piece builds"],
        ["pitch class", "notes.class.0", "twelve lanterns round the shore, one per pitch class, with their reflections"],
        ["chord", "notes.polyphony", "a bigger chord lays a brighter path of light on the water"],
        ["velocity", "notes.lastVelocity", "how bright a lantern flares"],
        ["mod wheel", "control.modwheel", "STRUCTURE: night falls: the sky and the lake darken, the sun's light "
         "leaves the facets, the lanterns brighten"],
        ["silence", "(no input)", "the glide goes on; the lake is glass"],
    ],
    "tier": "light: about 9,000 faceted triangles (plus their twins), two unlit material programs, no lights, no fog",
}


# ================================================================================================ the land
def crest(r, r0, r1, peak=0.45):
    """A range's profile across its band: 0 at both edges (under water), 1 at the crest. It leaves the water steeply
    (a shallow shore draws as a pale flat beach)."""
    t = (r - r0) / (r1 - r0)
    if t <= 0.0 or t >= 1.0:
        return 0.0
    if t < peak:
        return mx.smooth(0.0, peak, t) ** 0.45
    return mx.smooth(1.0, peak, t) ** 0.7


def range_height(r0, r1, base, amp, wl, seed, peak=0.45, sink=14.0):
    def h(x, z, r, th):
        c = crest(r, r0, r1, peak)
        n = mx.fbm(x / wl, z / wl, seed, 4, ridged=True)
        return c * (base + amp * n) - sink * (1.0 - c) ** 2 - 4.0
    return h


# (name, r0, r1, rings, segments, base height, relief, wavelength, seed, crest position, band light colour)
RANGES = [
    ("shore", 470.0, 820.0, 7, 150, 10.0, 70.0, 230.0, 3, 0.5, "#ffb38c"),
    ("main", 760.0, 1520.0, 10, 140, 55.0, 240.0, 420.0, 7, 0.42, "#ff9ab0"),
    ("far", 1440.0, 2420.0, 8, 120, 140.0, 380.0, 560.0, 13, 0.45, "#d6a0ff"),
    ("distant", 2300.0, 3900.0, 7, 96, 240.0, 600.0, 800.0, 21, 0.5, "#b8c4ff"),
]
BANDS = {"shore": "bass", "main": "audio.lowMid", "far": "audio.mid", "distant": "audio.highMid"}

# the island and the rocks: (seed, radius, height, sides, rings, position, lean)
ISLAND = [(31, 120.0, 104.0, 15, 7, (0.0, 0.0, 0.0), (0.12, -0.06)),
          (33, 62.0, 52.0, 11, 5, (92.0, 0.0, 58.0), (0.1, 0.05)),
          (35, 55.0, 34.0, 9, 4, (-86.0, 0.0, -48.0), (-0.1, 0.0)),
          (37, 40.0, 26.0, 8, 4, (30.0, 0.0, -105.0), (0.0, -0.12))]
ROCKS = [(41, 14.0, 13.0, 7, 3, 0.2, 228.0), (43, 22.0, 26.0, 7, 3, 1.1, 412.0), (45, 9.0, 8.0, 6, 2, 1.9, 238.0),
         (47, 30.0, 14.0, 8, 3, 2.7, 455.0), (49, 18.0, 21.0, 7, 3, 3.5, 396.0), (51, 12.0, 11.0, 6, 3, 4.4, 250.0),
         (53, 26.0, 30.0, 8, 3, 5.3, 470.0)]


def generate_meshes():
    """Write the land's GLBs (and their twins) into examples/sonic-abstract/meshes/. Deterministic."""
    out = {}
    for name, r0, r1, nr, nth, base, amp, wl, seed, peak, _col in RANGES:
        tris = mx.polar_range(r0, r1, nr, nth, range_height(r0, r1, base, amp, wl, seed, peak), seed=seed)
        out[name] = tris
    isl = []
    for seed, rad, hgt, sides, rings, pos, lean in ISLAND:
        isl += mx.translate(mx.rock(seed, rad, hgt, sides, rings, sink=6.0, lean=lean), pos)
    out["island"] = isl
    rk = []
    for seed, rad, hgt, sides, rings, ang, dist in ROCKS:
        rk += mx.translate(mx.rock(seed, rad, hgt, sides, rings, sink=3.0), (dist * math.sin(ang), 0.0,
                                                                            dist * math.cos(ang)))
    out["rocks"] = rk
    for name, tris in list(out.items()):
        out[name] = tris = mx.clip_above(tris, 0.0)
        mx.write_faceted(os.path.join(MESH_DIR, "da-%s.glb" % name), tris, name)
        mx.write_faceted(os.path.join(MESH_DIR, "da-%s-twin.glb" % name), mx.mirrored(tris), name + "Twin")
    return list(out)


# ================================================================================================ the painter's programs


def rock_program():
    """Every landform and its twin, unlit. A material op's constants are clamped to +-1000 (they are parameters), so
    distances are in DECAMETRES here. Ops (1-based, as the routes name them): 13 the sun on the facets (its
    direction), 15 the sunlit colour, 25/26 the haze away from / towards the sun, 32 what the water keeps. (A program
    is interpreted per fragment and this one covers half the frame: it carries nothing it does not need -- the
    waterline mist went for the frame rate.)"""
    L = list(S)
    return {
        "name": "daRock",
        "ops": [
            {"kind": "input", "dst": 0, "input": "worldPosition"},                                     # 1
            {"kind": "input", "dst": 1, "input": "normal"},                                            # 2
            {"kind": "input", "dst": 2, "input": "cameraDistance"},                                    # 3
            {"kind": "constant", "dst": 3, "constant": [0.1, 0.1, 0.1, 0.1]},                          # 4
            {"kind": "multiply", "dst": 2, "srcA": 2, "srcB": 3},                                      # 5 decametres
            {"kind": "swizzle", "dst": 3, "srcA": 0, "constant": [1.0, 1.0, 1.0, 1.0]},               # 6 y
            {"kind": "threshold", "dst": 4, "srcA": 3, "value": 0.0},                                  # 7 above water
            {"kind": "constant", "dst": 5, "constant": [0.0, 2.0, 0.0, 0.0]},                          # 8
            {"kind": "multiply", "dst": 5, "srcA": 5, "srcB": 4},                                      # 9
            {"kind": "constant", "dst": 6, "constant": [1.0, -1.0, 1.0, 1.0]},                         # 10
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 11 (1,sgn,1,1)
            {"kind": "multiply", "dst": 1, "srcA": 1, "srcB": 5},                                      # 12 twin lit as original
            {"kind": "gradient", "dst": 5, "srcA": 1, "constant": L + [0.0], "value": 1.0},            # 13 sun
            {"kind": "gradient", "dst": 6, "srcA": 1, "constant": [0.0, 1.0, 0.0, 0.0], "value": 1.0},  # 14 sky
            {"kind": "constant", "dst": 7, "constant": hexrgb(SUNLIT) + [1.0]},                        # 15
            {"kind": "multiply", "dst": 5, "srcA": 5, "srcB": 7},                                      # 16
            {"kind": "constant", "dst": 7, "constant": hexrgb(SKYLIT) + [1.0]},                        # 17
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 7},                                      # 18
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 19
            {"kind": "constant", "dst": 6, "constant": hexrgb(SHADOW) + [1.0]},                        # 20
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 21 facet
            {"kind": "input", "dst": 6, "input": "materialEmission"},                                  # 22 band light
            {"kind": "add", "dst": 5, "srcA": 5, "srcB": 6},                                           # 23
            {"kind": "input", "dst": 0, "input": "viewDirection"},                                     # 24
            {"kind": "constant", "dst": 6, "constant": hexrgb(HAZE_COOL) + [1.0]},                     # 25
            {"kind": "constant", "dst": 7, "constant": hexrgb(HAZE_WARM) + [1.0]},                     # 26
            {"kind": "gradient", "dst": 1, "srcA": 0, "constant": [-SH[0], 0.0, -SH[2], 0.5],
             "value": 0.5},                                                                             # 27 towards sun
            {"kind": "mixBy", "dst": 6, "srcA": 6, "srcB": 7, "srcC": 1},                              # 28 haze colour
            {"kind": "smoothstep", "dst": 1, "srcA": 2, "constant": [HAZE_NEAR, HAZE_FAR, 0.0, 0.0]},  # 29 haze
            {"kind": "power", "dst": 1, "srcA": 1, "value": HAZE_CURVE},                               # 30
            {"kind": "mixBy", "dst": 5, "srcA": 5, "srcB": 6, "srcC": 1},                              # 31 hazed
            {"kind": "constant", "dst": 7, "constant": list(WATER) + [1.0]},                           # 32 water keeps
            {"kind": "multiply", "dst": 6, "srcA": 5, "srcB": 7},                                      # 33
            {"kind": "mixBy", "dst": 5, "srcA": 6, "srcB": 5, "srcC": 4},                              # 34
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 5, "emissionIntensity": 1.0, "opacity": -1,
    }


HAZE_NEAR, HAZE_FAR, HAZE_CURVE = 20.0, 450.0, 0.85   # decametres: the haze from 200 m to 4.5 km


def sky_program():
    """The sky dome, short (it covers the whole frame): the gradient by elevation (horizon warm towards the sun, cool
    away; violet; the zenith), the sun's glow and disc; below the horizon -- the band nearer than the lake's disc --
    the far water's colour. Ops (1-based): 7/8 the horizon away from / towards the sun, 12 the violet, 15 the zenith,
    17 the sun's direction, 19 the glow, 23 the sun."""
    sx, sy, sz = S
    return {
        "name": "daSky",
        "ops": [
            {"kind": "input", "dst": 0, "input": "viewDirection"},                                     # 1 v (to camera)
            {"kind": "swizzle", "dst": 1, "srcA": 0, "constant": [1.0, 1.0, 1.0, 1.0]},               # 2 v.y
            {"kind": "threshold", "dst": 2, "srcA": 1, "value": 0.0},                                  # 3 below
            {"kind": "multiply", "dst": 1, "srcA": 1, "srcB": 1},                                      # 4
            {"kind": "power", "dst": 1, "srcA": 1, "value": 0.5},                                      # 5 |elevation|
            {"kind": "gradient", "dst": 3, "srcA": 0, "constant": [-SH[0], 0.0, -SH[2], 0.5],
             "value": 0.5},                                                                             # 6 towards sun
            {"kind": "constant", "dst": 4, "constant": hexrgb(HORIZON_COOL) + [1.0]},                  # 7
            {"kind": "constant", "dst": 5, "constant": hexrgb(HORIZON_WARM) + [1.0]},                  # 8
            {"kind": "mixBy", "dst": 4, "srcA": 4, "srcB": 5, "srcC": 3},                              # 9 horizon
            {"kind": "remap", "dst": 5, "srcA": 1, "value": 1.0, "constant": [0.0, 0.22, 0.0, 1.0]},  # 10
            {"kind": "power", "dst": 5, "srcA": 5, "value": 0.8},                                      # 11
            {"kind": "constant", "dst": 6, "constant": hexrgb(VIOLET) + [1.0]},                        # 12
            {"kind": "mixBy", "dst": 6, "srcA": 4, "srcB": 6, "srcC": 5},                              # 13
            {"kind": "remap", "dst": 5, "srcA": 1, "value": 1.0, "constant": [0.14, 0.8, 0.0, 1.0]},   # 14
            {"kind": "constant", "dst": 7, "constant": hexrgb(ZENITH) + [1.0]},                        # 15
            {"kind": "mixBy", "dst": 6, "srcA": 6, "srcB": 7, "srcC": 5},                              # 16 sky
            {"kind": "gradient", "dst": 5, "srcA": 0, "constant": [-sx, -sy, -sz, 0.0], "value": 1.0},  # 17 sun
            {"kind": "power", "dst": 7, "srcA": 5, "value": 7.0},                                      # 18
            {"kind": "constant", "dst": 3, "constant": hexrgb(GLOW, 0.75) + [1.0]},                    # 19 glow
            {"kind": "multiply", "dst": 7, "srcA": 7, "srcB": 3},                                      # 20
            {"kind": "add", "dst": 6, "srcA": 6, "srcB": 7},                                           # 21
            {"kind": "power", "dst": 7, "srcA": 5, "value": 1000.0},                                   # 22
            {"kind": "constant", "dst": 3, "constant": hexrgb(SUN, 9.0) + [1.0]},                      # 23 sun
            {"kind": "multiply", "dst": 7, "srcA": 7, "srcB": 3},                                      # 24
            {"kind": "add", "dst": 6, "srcA": 6, "srcB": 7},                                           # 25
            {"kind": "constant", "dst": 3, "constant": list(WATER) + [1.0]},                           # 26
            {"kind": "multiply", "dst": 4, "srcA": 4, "srcB": 3},                                      # 27 far water
            {"kind": "mixBy", "dst": 6, "srcA": 6, "srcB": 4, "srcC": 2},                              # 28
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 6, "emissionIntensity": 1.0, "opacity": -1,
    }


def water_program():
    """The lake's sky: a disc far below the waterline (behind the twins) that paints, by the view ray alone, the mirror
    image of the sky -- its gradient, the sun's glow and disc -- darker and bluer, broken by ripples, with the sun's
    path (unlit). The sky above the horizon is the engine's own (cheap); a program is interpreted per fragment, so this
    one runs only where there is water. Ops (1-based): 5/6 the horizon / zenith, 8 the sun's mirrored direction,
    10 the glow, 14 the sun, 19 the ripples (noise: its offset drifts), 20 the ripples' depth, 24 what the water keeps,
    29 the sun's path."""
    sx, sy, sz = S
    return {
        "name": "daWater",
        "ops": [
            {"kind": "input", "dst": 0, "input": "viewDirection"},                                     # 1 v (to camera)
            {"kind": "swizzle", "dst": 1, "srcA": 0, "constant": [1.0, 1.0, 1.0, 1.0]},               # 2 depression
            {"kind": "remap", "dst": 2, "srcA": 1, "value": 1.0, "constant": [0.0, 0.55, 0.0, 1.0]},   # 3
            {"kind": "power", "dst": 2, "srcA": 2, "value": 0.55},                                     # 4
            {"kind": "constant", "dst": 3, "constant": hexrgb(HORIZON_COOL) + [1.0]},                  # 5 horizon
            {"kind": "constant", "dst": 4, "constant": hexrgb(ZENITH) + [1.0]},                        # 6 zenith
            {"kind": "mixBy", "dst": 3, "srcA": 3, "srcB": 4, "srcC": 2},                              # 7 mirrored sky
            {"kind": "gradient", "dst": 4, "srcA": 0, "constant": [-sx, sy, -sz, 0.0], "value": 1.0},   # 8 the sun's image
            {"kind": "power", "dst": 5, "srcA": 4, "value": 7.0},                                      # 9
            {"kind": "constant", "dst": 6, "constant": hexrgb(GLOW, 0.75) + [1.0]},                    # 10 glow
            {"kind": "multiply", "dst": 5, "srcA": 5, "srcB": 6},                                      # 11
            {"kind": "add", "dst": 3, "srcA": 3, "srcB": 5},                                           # 12
            {"kind": "power", "dst": 5, "srcA": 4, "value": 1000.0},                                   # 13
            {"kind": "constant", "dst": 6, "constant": hexrgb(SUN, 9.0) + [1.0]},                      # 14 sun
            {"kind": "multiply", "dst": 5, "srcA": 5, "srcB": 6},                                      # 15
            {"kind": "add", "dst": 3, "srcA": 3, "srcB": 5},                                           # 16
            # ripples: bands of the view's depression (fast) broken along the horizon (slow); calm at the horizon
            {"kind": "constant", "dst": 5, "constant": [-11.0, 150.0, -11.0, 0.0]},                    # 17
            {"kind": "multiply", "dst": 5, "srcA": 0, "srcB": 5},                                      # 18
            {"kind": "noise", "dst": 5, "srcA": 5, "value": 1.0, "constant": [0.0, 0.0, 0.0, 0.0],
             "seed": 7},                                                                                 # 19 ripples
            {"kind": "remap", "dst": 5, "srcA": 5, "value": 1.0, "constant": [0.3, 0.7, 0.86, 1.14]},  # 20 depth
            {"kind": "smoothstep", "dst": 6, "srcA": 1, "constant": [0.004, 0.05, 0.0, 0.0]},          # 21 calm far off
            {"kind": "constant", "dst": 7, "constant": [1.0, 1.0, 1.0, 1.0]},                          # 22
            {"kind": "mixBy", "dst": 5, "srcA": 7, "srcB": 5, "srcC": 6},                              # 23
            {"kind": "constant", "dst": 6, "constant": list(WATER) + [1.0]},                           # 24 water keeps
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 5},                                      # 25
            {"kind": "multiply", "dst": 3, "srcA": 3, "srcB": 6},                                      # 26 reflected
            {"kind": "gradient", "dst": 6, "srcA": 0, "constant": [-SH[0], 0.0, -SH[2], 0.0], "value": 1.0},  # 27
            {"kind": "power", "dst": 6, "srcA": 6, "value": 45.0},                                     # 28
            {"kind": "constant", "dst": 7, "constant": hexrgb("#ffc9a0", 2.2) + [1.0]},                # 29 the path
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 7},                                      # 30
            {"kind": "multiply", "dst": 6, "srcA": 6, "srcB": 5},                                      # 31
            {"kind": "add", "dst": 3, "srcA": 3, "srcB": 6},                                           # 32
        ],
        "baseColor": -1, "metallic": -1, "roughness": -1, "emission": 3, "emissionIntensity": 1.0, "opacity": -1,
    }


def unlit(hexc="#000000", intensity=0.0, program="daRock", double=False):
    m = {"baseColor": [0.0, 0.0, 0.0], "emissiveColor": hexrgb(hexc), "emissiveIntensity": float(intensity),
         "roughness": 1.0, "metallic": 0.0, "unlit": True, "program": program}
    if double:
        m["doubleSided"] = True
    return m


def swell(axis_y=1.0):
    """AUDIO TOPOGRAPHY: the travelling wave field displaces every vertex vertically (a twin's, downward)."""
    return [{"kind": "field", "field": "swell", "amount": 0.0, "axis": [0.0, float(axis_y), 0.0], "space": "world",
             "alongNormal": False}]


def landform(s, name, band="#000000"):
    for twin in (False, True):
        s.proc(name + ("Twin" if twin else ""),
               {"kind": "mesh", "asset": "meshes/da-%s%s.glb" % (name, "-twin" if twin else "")},
               material=unlit(band, 0.0), deformers=swell(-1.0 if twin else 1.0))


LANDFORMS = [r[0] for r in RANGES] + ["island", "rocks"]


def instrument(s):
    """The modulation map (ABSTRACT-PLAN.md section 6)."""
    P = "procedural/%s/"
    # ---- AUDIO TOPOGRAPHY: the level sets how tall the waves rolling out through the mountains are (metres)
    for node in LANDFORMS:
        for suffix in ("", "Twin"):
            s.route(R("level", P % (node + suffix) + "deform/1/amount", 12.0, attackMs=400, decayMs=1800))
    # ---- SPECTRAL DEPTH: each range lights with its own band, near to far (its emission is added to the facets by the
    # program, before the haze)
    for name, *_r, band_col in RANGES:
        for suffix in ("", "Twin"):
            s.route(R(BANDS[name], P % (name + suffix) + "material/emissive", 0.16, attackMs=60, decayMs=700))
    # ---- BASS: the sun's path on the water brightens
    s.route(R("bass", "material/daWater/op/29/constant/constant", 1.2, attackMs=30, decayMs=500))
    # ---- KICK: the low sun flares across every facet that faces it; rings of light land on the water
    s.route(R("kick", "material/daRock/op/15/constant/constant", 0.5, attackMs=0, decayMs=380),
            R("kick", "particles/drops/burst", 14.0, threshold="binary", thresholdLevel=0.3))
    # ---- SNARE: a flash along the horizon (the sky's horizon and its image in the water)
    s.route(R("snare", "material/daSky/op/7/constant/constant", 0.25, attackMs=0, decayMs=260),
            R("snare", "material/daSky/op/8/constant/constant", 0.35, attackMs=0, decayMs=260),
            R("snare", "material/daWater/op/5/constant/constant", 0.25, attackMs=0, decayMs=260))
    # ---- MIDS: the water's ripples deepen; HIGHS: glints on the water, the sun's glow brightens
    s.route(R("audio.mid", "material/daWater/op/20/remap/constant", -0.25, comp=2, attackMs=80, decayMs=700),
            R("audio.mid", "material/daWater/op/20/remap/constant", 0.3, comp=3, attackMs=80, decayMs=700),
            R("audio.treble", "particles/glints/spawnRate", 900.0, attackMs=20, decayMs=250),
            R("audio.treble", "material/daSky/op/19/constant/constant", 0.5, attackMs=60, decayMs=500),
            R("audio.treble", "material/daWater/op/10/constant/constant", 0.5, attackMs=60, decayMs=500))
    # ---- TEMPO: the ripples drift with the beat's phase (the noise's offset)
    s.route(R("beatPhase", "material/daWater/op/19/noise/constant", 0.6, comp=0),
            R("beatPhase", "material/daWater/op/19/noise/constant", 0.4, comp=2))
    # ---- CENTROID: the palette drifts warmer or cooler, very slowly
    s.route(R("brightnessSlow", "post/grade/hueShift", 0.5, offset=-0.5, **VERY_SLOW))
    # ---- INTENSITY: STRUCTURE -- the ranges rise as the piece builds
    for name in ("main", "far", "distant"):
        for suffix in ("", "Twin"):
            s.route(R("intensity", P % (name + suffix) + "transform/scale", 0.22, comp=1, **VERY_SLOW))
    # ---- MIDI: twelve lanterns round the shore, one per pitch class (with their reflections); velocity is how bright;
    # a bigger chord lays a brighter path of light on the water
    for k in range(12):
        for suffix in ("", "Twin"):
            s.route(R("notes.class.%d" % k, P % ("lantern%d" % k + suffix) + "material/emissive", 60.0,
                      depth="lastVelocity", attackMs=0, decayMs=900))
    s.route(R("polyphony", "material/daWater/op/29/constant/constant", 2.0, **MEDIUM))
    # ---- MOD WHEEL: STRUCTURE -- night falls: the sky and its image darken, the sun's light leaves the facets, the
    # lanterns brighten
    wheel = s.modwheel()
    s.route(R(wheel, "material/daSky/op/15/constant/constant", 1.0, op="multiply", gain=-0.6, offset=1.0,
              attackMs=300, decayMs=300),
            R(wheel, "material/daSky/op/7/constant/constant", 1.0, op="multiply", gain=-0.7, offset=1.0,
              attackMs=300, decayMs=300),
            R(wheel, "material/daSky/op/8/constant/constant", 1.0, op="multiply", gain=-0.7, offset=1.0,
              attackMs=300, decayMs=300),
            R(wheel, "material/daSky/op/12/constant/constant", 1.0, op="multiply", gain=-0.6, offset=1.0,
              attackMs=300, decayMs=300),
            R(wheel, "material/daWater/op/5/constant/constant", 1.0, op="multiply", gain=-0.7, offset=1.0, attackMs=300, decayMs=300),
            R(wheel, "material/daRock/op/15/constant/constant", 1.0, op="multiply", gain=-0.8, offset=1.0, attackMs=300, decayMs=300),
            R(wheel, "material/daRock/op/25/constant/constant", 1.0, op="multiply", gain=-0.6, offset=1.0, attackMs=300, decayMs=300),
            R(wheel, "material/daRock/op/26/constant/constant", 1.0, op="multiply", gain=-0.6, offset=1.0, attackMs=300, decayMs=300))
    for k in range(12):
        for suffix in ("", "Twin"):
            s.route(R(wheel, "procedural/%s/material/emissive" % ("lantern%d" % k + suffix), 6.0, attackMs=300,
                      decayMs=300))


def camera_track(s):
    """A low glide round the lake: the circle of radius CAM_R. The view swings slowly (twice a circuit) between
    looking ahead along the glide (the far ranges coming) and looking in across the water at the island with the
    ranges sliding past behind it."""
    kp, kt = [], []
    steps = 64
    for i in range(steps + 1):
        u = i / steps
        th = THETA0 + 2.0 * math.pi * u
        pos = (CAM_R * math.sin(th), CAM_H + 2.5 * math.sin(4.0 * math.pi * u), CAM_R * math.cos(th))
        fwd = (math.cos(th), 0.0, -math.sin(th))            # d/dtheta of the position: counter-clockwise from above
        inward = (-math.sin(th), 0.0, -math.cos(th))
        yaw = math.radians(9.0 + 14.0 * (1.0 - math.cos(4.0 * math.pi * u)))   # 9 to 37 degrees in from ahead
        look = (fwd[0] * math.cos(yaw) + inward[0] * math.sin(yaw), fwd[2] * math.cos(yaw) + inward[2] * math.sin(yaw))
        tgt = (pos[0] + 500.0 * look[0], CAM_H - 36.0, pos[2] + 500.0 * look[1])
        kp.append({"time": round(PERIOD * u, 4), "value": [round(v, 3) for v in pos], "interp": "smooth"})
        kt.append({"time": round(PERIOD * u, 4), "value": [round(v, 3) for v in tgt], "interp": "smooth"})
    s.track("camera/position", kp, loop=PERIOD)
    s.track("camera/target", kt, loop=PERIOD)
    s.camera = {"mode": 1, "position": kp[0]["value"], "target": kt[0]["value"], "fov": 40.0, "orbitSpeed": 0.0}


def build():
    generate_meshes()
    s = kit.Scene(ID, TITLE, DESIGN)
    s.unshadowed_key()          # every material is unlit: the default key's shadow would be pure cost
    s.response = {"sensitivity": 0.5, "transient": 0.55, "sustain": 0.55, "attack": 1.0, "release": 1.1,
                  "floorDb": -44.0, "rangeDb": 42.0}     # mastered music does not saturate the levels
    # nothing is lit and nothing is fogged: the programs paint the light and the air
    s.environment = {
        "intensity": 0.0, "background": hexrgb(HORIZON_COOL), "fogColor": hexrgb(HAZE_COOL), "volumeDensity": 0.0,
        "skyIntensity": 1.0,
        "sky": {"enabled": True, "zenithColor": hexrgb(ZENITH), "horizonColor": hexrgb(HORIZON_COOL),
                "groundColor": hexrgb(HORIZON_COOL), "haze": 0.3, "sunIntensity": 0.0, "intensity": 1.0,
                "background": True, "useKeyLight": False},
    }
    s.program(rock_program())
    s.program(sky_program())
    s.program(water_program())

    # ---- the sky: a dome with a short program (it covers the frame); the sky in the lake: a disc 1 km below the
    # waterline, 30 km across, behind every twin, with the water's program (only where there is water). The band of
    # water nearer the horizon than the disc's edge is the dome's own far-water colour.
    s.proc("dome", {"kind": "sphere", "radius": 1000.0, "segments": 64, "rings": 32},
           material=unlit("#000000", 0.0, program="daSky", double=True),
           transform={"position": [0.0, 0.0, 0.0], "rotation": [0.0, 0.0, 0.0], "scale": [7.0, 7.0, 7.0]})
    s.proc("lakeSky", {"kind": "cylinder", "radius": 1000.0, "height": 1.0, "radialSegments": 64, "caps": True},
           material=unlit("#000000", 0.0, program="daWater"),
           transform={"position": [0.0, -1000.0, 0.0], "rotation": [0.0, 0.0, 0.0], "scale": [30.0, 1.0, 30.0]})

    # ---- AUDIO TOPOGRAPHY: a wave rolling outward from the island (a sine train, 900 m long, at 150 m/s); the routes
    # set how tall it is
    s.nodes.append({"name": "swell", "kind": "field", "field": {
        "kind": "wave", "waveGeometry": "cylindrical", "waveShape": "sine", "amplitude": 1.0, "wavelength": 900.0,
        "waveSpeed": 150.0, "waveWidth": 0.0, "axis": [0.0, 1.0, 0.0], "position": [0.0, 0.0, 0.0],
        "strength": 1.0}})

    # ---- the land: four ranges round the lake, the island, the rocks (each with its twin)
    for name, *_r, band in RANGES:
        landform(s, name, band)
    landform(s, "island")
    landform(s, "rocks")

    # ---- twelve lanterns on the shore, the pitch classes (C at the island's north, round clockwise), and their twins
    for k in range(12):
        a = -2.0 * math.pi * k / 12.0
        x, z = 540.0 * math.sin(a), 540.0 * math.cos(a)
        for twin in (False, True):
            s.proc("lantern%d" % k + ("Twin" if twin else ""), {"kind": "sphere", "radius": 2.0, "segments": 12,
                                                                  "rings": 8},
                   material={"baseColor": [0.0, 0.0, 0.0], "emissiveColor": hexrgb("#ffc890"),
                             "emissiveIntensity": 2.0, "roughness": 1.0, "metallic": 0.0, "unlit": True},
                   transform={"position": [x, -2.6 if twin else 2.6, z], "rotation": [0, 0, 0], "scale": [1, 1, 1]})

    # ---- glints on the water (the highs) and the rings of light where onsets land (drops that splash at y = 0)
    s.particles("glints", capacity=8000, seed=5, shape="disc", position=[0.0, 0.25, 0.0], extent=[520.0, 0.1, 520.0],
                direction=[0.0, 1.0, 0.0], spawnRate=60.0, lifetimeMin=0.12, lifetimeMax=0.4, spread=0.0,
                speedMin=0.0, speedMax=0.0, gravity=[0, 0, 0], drag=0.0, sizeStart=0.9, sizeEnd=0.0,
                colorStart=hexrgb("#fff2e0") + [1.0], colorEnd=hexrgb(HORIZON_WARM) + [0.0], emissive=5.0,
                blend="additive", turbulence=0.0)
    s.particles("drops", capacity=600, seed=9, shape="disc", position=[0.0, 0.6, 0.0], extent=[460.0, 0.1, 460.0],
                direction=[0.0, -1.0, 0.0], spawnRate=0.0, lifetimeMin=2.0, lifetimeMax=2.0, spread=0.0,
                speedMin=8.0, speedMax=8.0, gravity=[0, 0, 0], drag=0.0, sizeStart=2.4, sizeEnd=2.4,
                colorStart=hexrgb("#ffe6d8") + [0.75], colorEnd=hexrgb("#c9b6ff") + [0.0], emissive=2.5,
                blend="additive", turbulence=0.0, collision="splash", collisionHeight=0.0, splashLifetime=2.2,
                splashSize=7.0, ringThickness=0.06)

    # ---- the camera: a low glide round the lake, banking into the turn
    camera_track(s)
    s.track("camera/roll", [{"time": 0.0, "value": -2.5, "interp": "smooth"},
                            {"time": PERIOD * 0.5, "value": -4.0, "interp": "smooth"},
                            {"time": PERIOD, "value": -2.5, "interp": "smooth"}], loop=PERIOD)
    s.params_({"camera/lens/focalLength": 24.0, "post/bloom/intensity": 0.25, "post/bloom/threshold": 1.6,
               "post/bloom/emissionWeight": 1.0, "post/output/vignette": 0.3, "post/output/grain": 0.012,
               "post/tonemap/operator": 4})

    instrument(s)
    s.region("sky", box=[0.0, 0.0, 1.0, 0.42])
    s.region("lake", box=[0.0, 0.5, 1.0, 1.0])
    return s
