#include "scene/candidate_search.hpp"

#include "core/noise.hpp"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <limits>

namespace avgen::scene {
namespace {

// The first sixteen primes. One radical-inverse base per dimension; sixteen is more design-space
// dimensions than any subject here needs, and a Halton sequence in more than about twenty
// dimensions stops being better-distributed than random anyway.
constexpr std::array<std::uint32_t, 16> kPrimes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53};

// Radical inverse with Braaten-Weller digit scrambling, keyed by the seed. Unscrambled Halton in
// higher dimensions puts visible diagonal streaks through the sample set -- the well-known
// correlation between bases -- and a parameter sweep that walks a diagonal is a sweep that never
// tries half the space.
float scrambledRadicalInverse(std::uint32_t index, std::uint32_t base, std::uint32_t seed) {
    const float invBase = 1.0f / static_cast<float>(base);
    float f = invBase;
    float result = 0.0f;
    std::uint32_t i = index;
    std::uint32_t digit = 0;
    while (i > 0 && result + f > result) {
        const std::uint32_t d = i % base;
        // A per-digit-position permutation of {0..base-1}, generated by a hash. Cheap, and enough
        // to break the inter-base correlation.
        const auto offset = static_cast<std::uint32_t>(noise::hashIndex(seed, base * 977u + digit, 91u) *
                                                       static_cast<float>(base));
        const std::uint32_t scrambled = (d + offset) % base;
        result += static_cast<float>(scrambled) * f;
        i /= base;
        f *= invBase;
        ++digit;
    }
    return std::min(result, 0.9999999f);
}

float featureDistance(std::span<const float> a, std::span<const float> b) {
    const std::size_t n = std::min(a.size(), b.size());
    float sum = 0.0f;
    for (std::size_t i = 0; i < n; ++i) {
        const float d = a[i] - b[i];
        sum += d * d;
    }
    return std::sqrt(sum);
}

} // namespace

float MetricBand::score(float value) const {
    if (!std::isfinite(value)) {
        return floorScore;
    }
    if (value >= idealLow && value <= idealHigh) {
        return 1.0f;
    }
    if (value < idealLow) {
        if (value <= min) {
            return floorScore;
        }
        const float t = (value - min) / std::max(idealLow - min, 1e-6f);
        return floorScore + (1.0f - floorScore) * t;
    }
    if (value >= max) {
        return floorScore;
    }
    const float t = (max - value) / std::max(max - idealHigh, 1e-6f);
    return floorScore + (1.0f - floorScore) * t;
}

Result<void> MetricBand::validate(std::string_view owner) const {
    if (!std::isfinite(min) || !std::isfinite(max) || !std::isfinite(idealLow) || !std::isfinite(idealHigh)) {
        // This is the monotonicity rule, enforced. An infinite bound is exactly how a band becomes
        // "more is better", and the whole design rests on that being impossible to express.
        return fail("candidate band '{}': bounds must be finite, or the component is monotone", owner);
    }
    if (!(min <= idealLow && idealLow <= idealHigh && idealHigh <= max)) {
        return fail("candidate band '{}': expected min <= idealLow <= idealHigh <= max, got {} {} {} {}", owner,
                    min, idealLow, idealHigh, max);
    }
    if (max <= min) {
        return fail("candidate band '{}': max {} must exceed min {}", owner, max, min);
    }
    if (floorScore < 0.0f || floorScore >= 1.0f) {
        return fail("candidate band '{}': floorScore {} must be in [0, 1)", owner, floorScore);
    }
    return {};
}

const ScoredMetric* CandidateRecord::metric(std::string_view name) const {
    for (const ScoredMetric& m : metrics) {
        if (m.name == name) {
            return &m;
        }
    }
    return nullptr;
}

float scoreCandidate(const CandidateSubject& subject, CandidateRecord& record) {
    float weighted = 0.0f;
    float total = 0.0f;
    for (const ScoreComponent& component : subject.components()) {
        float value = 0.0f;
        bool found = false;
        for (ScoredMetric& m : record.metrics) {
            if (m.name == component.name) {
                value = m.value;
                m.score = component.band.score(value);
                m.weight = component.weight;
                found = true;
                break;
            }
        }
        if (!found) {
            // A declared component the subject did not measure scores its floor rather than being
            // skipped. Skipping would silently reweight every other component, which is a scoring
            // change disguised as a missing value.
            ScoredMetric missing;
            missing.name = component.name;
            missing.value = std::numeric_limits<float>::quiet_NaN();
            missing.score = component.band.floorScore;
            missing.weight = component.weight;
            record.metrics.push_back(missing);
            weighted += component.weight * component.band.floorScore;
            total += component.weight;
            continue;
        }
        weighted += component.weight * component.band.score(value);
        total += component.weight;
    }
    record.score = total > 0.0f ? weighted / total : 0.0f;
    return record.score;
}

std::vector<float> haltonPoint(std::uint32_t index, int dimensions, std::uint32_t seed) {
    std::vector<float> point;
    const int n = std::clamp(dimensions, 0, static_cast<int>(kPrimes.size()));
    point.reserve(static_cast<std::size_t>(n));
    for (int d = 0; d < n; ++d) {
        point.push_back(scrambledRadicalInverse(index + 1, kPrimes[static_cast<std::size_t>(d)], seed));
    }
    return point;
}

std::vector<CandidateRecord> selectDiverse(std::span<const CandidateRecord> ranked, float radius, int limit) {
    std::vector<CandidateRecord> kept;
    for (const CandidateRecord& candidate : ranked) {
        if (limit > 0 && static_cast<int>(kept.size()) >= limit) {
            break;
        }
        bool tooClose = false;
        if (radius > 0.0f) {
            for (const CandidateRecord& accepted : kept) {
                if (featureDistance(candidate.features, accepted.features) < radius) {
                    tooClose = true;
                    break;
                }
            }
        }
        if (!tooClose) {
            kept.push_back(candidate);
        }
    }
    return kept;
}

Result<SearchResult> searchCandidates(const CandidateSubject& subject, const SearchSettings& settings) {
    if (settings.population < 1) {
        return fail("candidate search: population {} must be at least 1", settings.population);
    }
    if (settings.generations < 1) {
        return fail("candidate search: generations {} must be at least 1", settings.generations);
    }
    for (const ScoreComponent& component : subject.components()) {
        if (auto ok = component.band.validate(component.name); !ok) {
            return std::unexpected(ok.error());
        }
        if (component.weight <= 0.0f) {
            return fail("candidate search: component '{}' has non-positive weight {}", component.name,
                        component.weight);
        }
    }

    const auto started = std::chrono::steady_clock::now();
    SearchResult result;
    std::vector<CandidateRecord> elite;
    std::uint32_t nextIndex = 0;

    for (int generation = 0; generation < settings.generations; ++generation) {
        std::vector<CandidateRecord> population;
        for (int i = 0; i < settings.population; ++i) {
            const std::uint32_t index = nextIndex++;
            const std::vector<float> u = haltonPoint(index, subject.dimensions(), settings.seed);

            nlohmann::json parameters;
            if (generation == 0 || elite.empty()) {
                parameters = subject.sample(u);
            } else {
                // Hill climbing around the survivors. Which survivor is chosen comes from the same
                // deterministic hash stream as everything else, so a refinement generation is as
                // reproducible as the initial sweep.
                const auto pick = static_cast<std::size_t>(
                    noise::hashIndex(settings.seed, index, 131u) * static_cast<float>(elite.size()));
                parameters = subject.perturb(elite[std::min(pick, elite.size() - 1)].parameters, u,
                                             settings.perturbScale);
            }

            CandidateRecord record;
            record.index = index;
            record.generation = generation;
            record.parameters = parameters;
            const auto measureStart = std::chrono::steady_clock::now();
            if (auto ok = subject.measure(parameters, record); !ok) {
                ++result.rejected;
                continue;
            }
            record.evaluateMs =
                std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - measureStart).count() -
                record.generateMs;
            scoreCandidate(subject, record);
            population.push_back(std::move(record));
        }
        if (population.empty()) {
            continue;
        }
        result.all.insert(result.all.end(), population.begin(), population.end());

        // The elite pool is drawn from everything seen so far, not just this generation, so a good
        // candidate found early is never lost to a bad refinement step.
        std::vector<CandidateRecord> pool = result.all;
        std::sort(pool.begin(), pool.end(), [](const CandidateRecord& a, const CandidateRecord& b) {
            // Index breaks ties so the ordering does not depend on the sort's stability.
            return a.score != b.score ? a.score > b.score : a.index < b.index;
        });
        elite = selectDiverse(pool, settings.diversityRadius, settings.elite);
    }

    if (result.all.empty()) {
        return fail("candidate search: every one of {} candidates failed to build",
                    settings.population * settings.generations);
    }
    std::vector<CandidateRecord> pool = result.all;
    std::sort(pool.begin(), pool.end(), [](const CandidateRecord& a, const CandidateRecord& b) {
        return a.score != b.score ? a.score > b.score : a.index < b.index;
    });
    result.ranked = selectDiverse(pool, settings.diversityRadius, 0);
    result.totalMs = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - started).count();
    return result;
}

nlohmann::json SearchResult::report() const {
    nlohmann::json j;
    j["candidates"] = all.size();
    j["rejected"] = rejected;
    j["totalMs"] = totalMs;
    nlohmann::json list = nlohmann::json::array();
    for (const CandidateRecord& record : ranked) {
        nlohmann::json entry;
        entry["index"] = record.index;
        entry["generation"] = record.generation;
        entry["score"] = record.score;
        nlohmann::json metrics = nlohmann::json::object();
        for (const ScoredMetric& m : record.metrics) {
            metrics[m.name] = {{"value", m.value}, {"score", m.score}};
        }
        entry["metrics"] = std::move(metrics);
        entry["parameters"] = record.parameters;
        list.push_back(std::move(entry));
    }
    j["ranked"] = std::move(list);
    return j;
}

} // namespace avgen::scene
