#pragma once

// Animation retargeting (ADR-548): moving a clip authored on one skeleton onto another.
//
// **This is the unit Phase 0 named as the blocking dependency for everything else**
// (`docs/design/autonomous-character-animation.md` §1.5, §12.1). Before it, `Importer::importClips`
// could only fill the rigs built in the same `loadGltf` call, so a character's motion was whatever
// shipped inside its own file -- which is why each of the six alien variants carries its own copy
// of all 26 animations, 3.9 MB of each 4.5 MB file. It is also why the 100STYLE corpus (CC BY 4.0,
// four million frames) is unreachable: there is nowhere to put it.
//
// **Offline.** Retargeting samples a clip on a grid and builds a new one. Nothing here runs per
// frame; a runtime reads the result.
//
// **The profile holds the character knowledge, the engine holds none.** There is no `if (alien)`
// anywhere in this file and there is no list of joint names either. The three rig families in this
// repository share no joint name at all -- the alien calls its head `head.x`, the bull `Head01`,
// the chicken `Head` -- so a built-in map would be a silent no-op on two of the three. A profile is
// data, authored once per rig pair or generated by role matching and then corrected by hand.

#include "scene/skeleton.hpp"

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace avgen::scene {

struct AnimationClip;

// ---- roles ---------------------------------------------------------------------------------------
//
// A vocabulary for "the same bone on a different body". Roles are how an automatic mapper guesses
// and how a human corrects it; the profile that comes out the other side is joint names, because a
// role is a convenience and a name is a fact.
enum class HumanoidRole : std::uint8_t {
    None,
    Hips, Spine, Chest, Neck, Head,
    LeftShoulder, LeftUpperArm, LeftLowerArm, LeftHand,
    RightShoulder, RightUpperArm, RightLowerArm, RightHand,
    LeftUpperLeg, LeftLowerLeg, LeftFoot, LeftToe,
    RightUpperLeg, RightLowerLeg, RightFoot, RightToe,
    Count,
};
[[nodiscard]] const char* humanoidRoleName(HumanoidRole role);
[[nodiscard]] bool humanoidRoleFromName(std::string_view name, HumanoidRole& out);

// ---- the profile ---------------------------------------------------------------------------------

struct JointMapping {
    std::string source;
    std::string target;
    HumanoidRole role = HumanoidRole::None; // advisory; the names are what bind
};

struct RetargetProfile {
    std::string name;
    std::string sourceSkeleton; // advisory labels, for provenance and for a mismatch warning
    std::string targetSkeleton;
    std::vector<JointMapping> joints;

    // Which source joint's translation becomes the target's travel. Empty means the mapping whose
    // role is `Hips`, and failing that the first mapping.
    std::string rootJoint;

    // Whether only the root joint's translation is carried across.
    //
    // **False by default, and that default is a measurement.** The textbook retarget is
    // rotation-only for everything but the root, because copying translation stretches the target
    // onto the source's proportions. That is right for a rig whose motion lives in its rotations,
    // and the Glowmere alien is not one: it is an Auto-Rig Pro deform export, its hierarchy is
    // nearly flat (18 joints hang directly off the armature), and **all 89 joints carry an animated
    // translation channel in every clip**. Measured: a rotation-only retarget of `Walking` onto the
    // alien's own skeleton reproduces orientations to 0.04 degrees and misses `foot.l` by 0.38
    // model units, because most of that clip's motion is not in its rotations.
    //
    // So the default carries each joint's translation as a **deviation from its own rest**, scaled
    // by the ratio of the two rigs' rest bone lengths at that joint. On identical skeletons that is
    // the identity; on a target twice the size the deviation doubles; and a joint the source never
    // translates contributes nothing, so a rotation-driven rig still produces rotation-only output.
    bool rootTranslationOnly = false;

    // How the root's translation is scaled from source units to target ones. 0 means "derive it
    // from the two rest poses", as the ratio of the mapped hips' heights above the skeleton root,
    // which is the standard proxy for leg length and is measurable rather than authored.
    float rootScale = 0.0f;

    // Sampling rate for the generated clip, in hertz. The source's own keys are not reused: a
    // retarget is a resampling, because the target's joints are not the source's and a key that
    // meant something on one rig means nothing on the other.
    float sampleRate = 30.0f;

    friend bool operator==(const RetargetProfile&, const RetargetProfile&) = default;
};

// ---- the binding ---------------------------------------------------------------------------------

// A profile resolved against two real skeletons. Built once, used for every clip.
struct RetargetBinding {
    struct Link {
        int source = -1;
        int target = -1;
        HumanoidRole role = HumanoidRole::None;
        // The rest-pose correction: the rotation that takes the SOURCE joint's rest orientation to
        // the TARGET joint's. A retarget copies model-space orientation, and two rigs almost never
        // agree about which way a bone's local axes point -- a bone that is "straight down the leg"
        // on one may be "down and twisted 40 degrees" on the other. Without this the character
        // arrives in a pose that is the animation composed with the difference between two bind
        // poses, which looks like a badly broken joint rather than like a mapping error.
        glm::quat delta{1.0f, 0.0f, 0.0f, 0.0f};
        // How a translation deviation at this joint scales from source units to target ones: the
        // ratio of the two rest offsets' lengths, falling back to the whole-rig `rootScale` where
        // one of them is degenerate (a joint sitting exactly on its parent).
        float translationScale = 1.0f;
    };
    std::vector<Link> links;
    int rootLink = -1;      // index into `links`, or -1
    float rootScale = 1.0f; // resolved from the profile or derived from the rest poses
    bool rootTranslationOnly = false; // carried from the profile
    // Names the profile asked for that one of the skeletons does not carry, and mappings dropped
    // for any other reason. A retarget that silently ignored half its map would produce a character
    // whose legs animate and whose arms do not, and nothing would say why.
    std::vector<std::string> problems;

    [[nodiscard]] bool usable() const { return !links.empty(); }
};

[[nodiscard]] RetargetBinding bindRetarget(const Skeleton& source, const Skeleton& target,
                                           const RetargetProfile& profile);

// ---- the retarget ---------------------------------------------------------------------------------

struct RetargetStats {
    std::uint32_t frames = 0;
    std::uint32_t channels = 0;
    // The worst and mean angle, in degrees, between a mapped joint's model-space orientation on the
    // source and on the target, over every sampled frame. This is the retarget's own error measure:
    // zero means the target reproduces the source's orientations exactly, which is what a retarget
    // between identical skeletons must achieve and is the arm that catches a broken `delta`.
    float worstOrientationError = 0.0f;
    float meanOrientationError = 0.0f;
    // How much the target's bone lengths changed over the clip. Must be zero: a retarget rotates,
    // it does not stretch. A non-zero value means translation leaked into a non-root joint.
    float worstBoneLengthError = 0.0f;
};

// Produce a clip that plays `clip` (authored on `source`) on `target`.
//
// **The generated clip's time base is normalised to zero.** A source clip need not start at zero --
// Blender's exporter writes the frame range it was given, and this repository's alien pack starts at
// 1/30 s (ADR-204) -- so source second `clip.start + t` is output second `t`. A caller comparing the
// two must allow for it; one that does not sees a one-frame offset and mistakes it for error.
//
// The generated clip carries rotation channels for every mapped target joint, plus a translation
// channel for the root. It does NOT carry scale channels and it does not carry translation for any
// other joint -- see `RetargetProfile::rootJoint`.
[[nodiscard]] AnimationClip retargetClip(const AnimationClip& clip, const Skeleton& source,
                                         const Skeleton& target, const RetargetBinding& binding,
                                         RetargetStats* stats = nullptr);

// ---- automatic correspondence ----------------------------------------------------------------------

// Guess a profile by matching joint names against a role vocabulary, on both skeletons.
//
// **A convenience, never an assumption.** It is right often enough to save an hour and wrong often
// enough that the result must be looked at: it will find `UpperLegB.L` and `LeftUpLeg` and it will
// not find the alien's `leg_stretch.l`, because nothing about that name says "knee". What it
// returns is a profile a human edits, and the roles it could not fill are listed so that the gaps
// are visible rather than implied by absence.
struct RoleGuess {
    RetargetProfile profile;
    std::vector<HumanoidRole> unmatchedSource;
    std::vector<HumanoidRole> unmatchedTarget;
};
[[nodiscard]] RoleGuess guessRetargetProfile(const Skeleton& source, const Skeleton& target);

// Which role, if any, a joint name looks like. Exposed because it is the whole of what the guess
// knows and a test that could only reach it through two skeletons would be testing three things.
[[nodiscard]] HumanoidRole roleForJointName(std::string_view name);

} // namespace avgen::scene
