#include "rendering/shadow_math.hpp"

#include <glm/gtc/matrix_transform.hpp>

#include <algorithm>
#include <cmath>

namespace avgen::rendering {

namespace {

glm::vec3 safeNormalize(const glm::vec3& v, const glm::vec3& fallback) {
    const float len2 = glm::dot(v, v);
    return len2 > 1e-12f ? v * (1.0f / std::sqrt(len2)) : fallback;
}

glm::vec3 stableUp(const glm::vec3& direction) {
    return std::abs(direction.y) > 0.99f ? glm::vec3(0.0f, 0.0f, 1.0f) : glm::vec3(0.0f, 1.0f, 0.0f);
}

} // namespace

std::vector<float> cascadeSplits(float nearPlane, float farPlane, std::uint32_t count, float lambda) {
    const std::uint32_t n = std::clamp(count, 1u, kMaxCascades);
    const float near = std::max(nearPlane, 1e-3f);
    const float far = std::max(farPlane, near * 1.001f);
    const float ratio = far / near;
    std::vector<float> splits;
    splits.reserve(n);
    for (std::uint32_t i = 1; i <= n; ++i) {
        const float p = static_cast<float>(i) / static_cast<float>(n);
        const float logSplit = near * std::pow(ratio, p);
        const float uniformSplit = near + (far - near) * p;
        splits.push_back(std::clamp(lambda, 0.0f, 1.0f) * logSplit + (1.0f - std::clamp(lambda, 0.0f, 1.0f)) * uniformSplit);
    }
    splits.back() = far;
    return splits;
}

std::array<glm::vec3, 8> frustumCorners(const glm::mat4& invViewProj) {
    // WebGPU clip space: x, y in [-1, 1], z in [0, 1].
    constexpr std::array<glm::vec3, 8> ndc = {
        glm::vec3(-1.0f, -1.0f, 0.0f), glm::vec3(1.0f, -1.0f, 0.0f), glm::vec3(1.0f, 1.0f, 0.0f),
        glm::vec3(-1.0f, 1.0f, 0.0f),  glm::vec3(-1.0f, -1.0f, 1.0f), glm::vec3(1.0f, -1.0f, 1.0f),
        glm::vec3(1.0f, 1.0f, 1.0f),   glm::vec3(-1.0f, 1.0f, 1.0f)};
    std::array<glm::vec3, 8> out{};
    for (std::size_t i = 0; i < ndc.size(); ++i) {
        const glm::vec4 h = invViewProj * glm::vec4(ndc[i], 1.0f);
        out[i] = glm::vec3(h) / h.w;
    }
    return out;
}

ShadowView fitDirectionalCascade(const glm::mat4& invViewProj, float cameraNear, float cameraFar,
                                 float nearDepth, float farDepth, const glm::vec3& lightDirection,
                                 std::uint32_t resolution, float casterDistance) {
    const std::array<glm::vec3, 8> corners = frustumCorners(invViewProj);
    const float span = std::max(cameraFar - cameraNear, 1e-4f);
    const float t0 = std::clamp((nearDepth - cameraNear) / span, 0.0f, 1.0f);
    const float t1 = std::clamp((farDepth - cameraNear) / span, 0.0f, 1.0f);

    // The sub-frustum corners: view depth varies linearly along each frustum edge.
    std::array<glm::vec3, 8> slice{};
    for (std::size_t i = 0; i < 4; ++i) {
        const glm::vec3 rayStart = corners[i];
        const glm::vec3 rayEnd = corners[i + 4];
        slice[i] = rayStart + (rayEnd - rayStart) * t0;
        slice[i + 4] = rayStart + (rayEnd - rayStart) * t1;
    }
    // Bounding sphere: stable under camera rotation, which is what stops the shadow edges swimming.
    glm::vec3 center(0.0f);
    for (const glm::vec3& c : slice) {
        center += c;
    }
    center /= static_cast<float>(slice.size());
    float radius = 0.0f;
    for (const glm::vec3& c : slice) {
        radius = std::max(radius, glm::length(c - center));
    }
    radius = std::max(std::ceil(radius * 16.0f) / 16.0f, 1e-3f); // quantised so it stops jittering

    const glm::vec3 dir = safeNormalize(lightDirection, glm::vec3(0.0f, -1.0f, 0.0f));
    // How far behind the cascade the light's near plane sits, so casters outside the visible range
    // still reach it. Every metre of pull-back costs depth precision, so it is kept tight.
    const float back = std::clamp(casterDistance, radius * 0.5f, radius * 3.0f);
    const float texel = 2.0f * radius / static_cast<float>(std::max(resolution, 1u));

    // Texel snapping: the cascade's centre is quantised to a light-space grid that is anchored to
    // the world origin, so the shadow map re-rasterises onto the same texel grid frame after frame
    // and edges stop crawling as the camera moves.
    //
    // The anchor is the whole point, and getting it wrong is silent. Snapping in a light space
    // built *around the cascade* -- `lookAt(eye, center, up)` -- cannot work, because that matrix
    // sends `center` to the light-space origin by construction: the value being floored is exactly
    // zero every frame, so the snap is a no-op. Worse than a no-op, in fact. Zero carries float
    // error of either sign, and `floor` maps the two signs to 0 and -texel, so the window jumped a
    // whole texel back and forth for a millimetre of camera motion -- shimmer generated by the code
    // written to prevent it.
    //
    // A rotation-only basis at the origin has no such degeneracy: `center` lands wherever the world
    // puts it, and flooring genuinely quantises.
    const glm::mat4 lightBasis = glm::lookAt(glm::vec3(0.0f), dir, stableUp(dir));
    glm::vec3 centerLs = glm::vec3(lightBasis * glm::vec4(center, 1.0f));
    centerLs.x = std::floor(centerLs.x / texel) * texel;
    centerLs.y = std::floor(centerLs.y / texel) * texel;
    const glm::vec3 snapped = glm::vec3(glm::inverse(lightBasis) * glm::vec4(centerLs, 1.0f));

    const glm::vec3 eye = snapped - dir * (radius + back);
    const glm::mat4 lightView = glm::lookAt(eye, snapped, stableUp(dir));

    const float zFar = back + 2.0f * radius;
    const glm::mat4 proj = glm::ortho(-radius, radius, -radius, radius, 0.01f, zFar);

    ShadowView view;
    view.viewProj = proj * lightView;
    view.texelWorldSize = texel;
    view.depthRange = zFar;
    view.farDistance = farDepth;
    view.cascade = true;
    return view;
}

ShadowView fitSpotShadow(const scene::PunctualLight& light, std::uint32_t resolution, float range) {
    const glm::vec3 dir = safeNormalize(light.direction, glm::vec3(0.0f, -1.0f, 0.0f));
    const float far = std::max(range, 0.5f);
    const float near = std::max(far * 0.005f, 0.02f);
    const float fov = std::clamp(light.outerConeAngle * 2.0f * 1.05f, 0.05f, 3.0f);
    const glm::mat4 view = glm::lookAt(light.position, light.position + dir, stableUp(dir));
    const glm::mat4 proj = glm::perspective(fov, 1.0f, near, far);
    ShadowView out;
    out.viewProj = proj * view;
    // A texel at the far plane, which is the conservative end of the range.
    out.texelWorldSize = 2.0f * std::tan(fov * 0.5f) * far / static_cast<float>(std::max(resolution, 1u));
    out.depthRange = far - near;
    out.farDistance = far;
    out.cascade = false;
    return out;
}

std::uint32_t pointShadowFace(glm::vec3 fromLight) {
    const glm::vec3 a = glm::abs(fromLight);
    if (a.x >= a.y && a.x >= a.z) {
        return fromLight.x > 0.0f ? 0u : 1u;
    }
    if (a.y >= a.z) {
        return fromLight.y > 0.0f ? 2u : 3u;
    }
    return fromLight.z > 0.0f ? 4u : 5u;
}

std::array<ShadowView, kPointShadowFaces> fitPointShadow(const scene::PunctualLight& light,
                                                         std::uint32_t resolution, float range) {
    // The face axes in the order `pointShadowFace` returns, with an up that is never parallel to the
    // forward axis -- the ±Y faces take Z, everything else takes Y, which is the standard cube
    // convention and is why a lookAt here never degenerates.
    static constexpr glm::vec3 kForward[kPointShadowFaces] = {
        {1.0f, 0.0f, 0.0f},  {-1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f},
        {0.0f, -1.0f, 0.0f}, {0.0f, 0.0f, 1.0f},  {0.0f, 0.0f, -1.0f}};
    static constexpr glm::vec3 kUp[kPointShadowFaces] = {
        {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 1.0f},
        {0.0f, 0.0f, 1.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f, 0.0f}};

    const float far = std::max(range, 0.5f);
    const float near = std::max(far * 0.005f, 0.02f);
    // A shade over ninety degrees. Exactly ninety tiles the cube with no overlap, and a PCF kernel
    // at a face's edge then samples outside it -- which `shadowLookup` reports as invalid and the
    // shading pass reads as *unshadowed*, drawing a bright seam along every face boundary. The
    // overlap costs nothing: the face is still chosen by the dominant axis.
    constexpr float kFaceFov = 1.5707963f * 1.04f;

    std::array<ShadowView, kPointShadowFaces> out{};
    for (std::uint32_t f = 0; f < kPointShadowFaces; ++f) {
        const glm::mat4 view = glm::lookAt(light.position, light.position + kForward[f], kUp[f]);
        const glm::mat4 proj = glm::perspective(kFaceFov, 1.0f, near, far);
        out[f].viewProj = proj * view;
        out[f].texelWorldSize =
            2.0f * std::tan(kFaceFov * 0.5f) * far / static_cast<float>(std::max(resolution, 1u));
        out[f].depthRange = far - near;
        out[f].farDistance = far;
        out[f].cascade = false;
        out[f].cube = true;
    }
    return out;
}

} // namespace avgen::rendering
