#!/usr/bin/env python3
"""Emit the Glowmere Atmospherics demonstration scene and project (ADR-230, brief section 11).

Derived from `glowmere-valley-2` rather than authored fresh: the point of the demonstration is the
two new effects, and a second valley would be a second thing to keep in step. The scene is Glowmere's
scene plus an `atmosphericEffects` array; the project is Glowmere's project with a camera that looks
at the sky, the effects' audio routes, and a `sequence` block that fires them.

Why a separate example rather than an edit to `glowmere-valley-2`:

  * Section 11 asks for an arrangement where the effects can be viewed separately and together, and
    warns against permanently cluttering every shot. Glowmere's own 253-second cut is composed for
    its mushrooms, and most of its shots point at the ground.
  * `glowmere-valley-2.scene.json` is generated by `tools/make_glowmere_valley_2.py` and fingerprinted
    by `tests/unit/test_glowmere_valley_2.cpp`. Hand-adding effects to it would drift from its own
    generator, which is the failure that test exists to catch.

The preset values come from `avgen_atmos_presets`, which is the engine's own `applyCometStyle` /
`applyAuroraStyle`, so nothing here holds a second copy of a tuned radiance.

    tools/make_glowmere_atmospherics.py [--presets path/to/avgen_atmos_presets]
"""

import argparse
import hashlib
import json
import math
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_SCENE = os.path.join(REPO, "examples/world/glowmere-valley-2.scene.json")
SRC_PROJ = os.path.join(REPO, "examples/world/glowmere-valley-2.json")
OUT_SCENE = os.path.join(REPO, "examples/world/glowmere-atmospherics.scene.json")
OUT_PROJ = os.path.join(REPO, "examples/world/glowmere-atmospherics.json")

# ---- the demonstration's shape --------------------------------------------------------------------
#
# Thirty seconds, arranged so each effect can be judged on its own before they are judged together.
# The timecodes are the deliverable: section 14 asks for ten things to be demonstrated and this is
# where each of them is.
#
#   0.0 -  6.0   the aurora alone, fading up out of the night
#   6.0 - 15.0   + the hero comet, cyan core and violet tail, crossing left to right
#  15.0 - 24.0   + the rainbow comet, crossing the other way
#  20.5 - 28.0   + a three-comet burst (emerald, magenta, a subtle shooting star)
#  throughout    the aurora answers the music; the ground takes a wash from both
DURATION = 30.0

# The camera. Glowmere's own cut points mostly at the ground -- its subjects are mushrooms -- so the
# demonstration authors its own move: a long dolly across the valley floor with the horizon held low
# in frame, which is what puts the sky on screen and what gives the comets something to have
# parallax against. 216 m of travel is about 5 degrees of shift at the hero comet's 2600 m, which is
# visible against the stars and is the whole difference between a celestial object and a decal.
CAM_START = [-108.0, 34.0, -52.0]
CAM_END = [104.0, 44.0, 28.0]
# Aimed up and across. The elevation works out at about +12 degrees, so with the project's 40-degree
# vertical field of view the frame runs from roughly -8 to +32 degrees: terrain along the bottom
# edge, and the aurora's full height above it.
AIM_AZIMUTH = 42.0     # degrees clockwise from +Z
AIM_ELEVATION = 12.0   # degrees above the horizon
AIM_DISTANCE = 260.0

# Where the comets cross, in the same sky coordinates the effect authors in: azimuth clockwise from
# +Z, elevation above the horizon. All of them are laid across the camera's bearing so the crossing
# happens on screen rather than behind the viewer.
COMETS = [
    # (preset, effect name, window start, window seconds, path overrides)
    # The hero crossing: enters top-left, sweeps down and right across the whole frame, exits low.
    ("Bioluminescent Cyan", "Hero Comet", 6.0, 9.5,
     dict(startAzimuth=-2.0, startElevation=30.0, endAzimuth=86.0, endElevation=2.0,
          distance=2600.0, travelSeconds=7.6, arcLift=180.0, curvature=-120.0)),
    # ...and the rainbow comet back the other way, so the two do not read as one effect repeated.
    ("Rainbow Cosmic", "Rainbow Comet", 15.0, 9.0,
     dict(startAzimuth=88.0, startElevation=26.0, endAzimuth=2.0, endElevation=4.0,
          distance=2300.0, travelSeconds=7.2, arcLift=210.0, curvature=150.0)),
    ("Emerald Teal", "Burst Emerald", 20.5, 7.5,
     dict(startAzimuth=12.0, startElevation=28.0, endAzimuth=66.0, endElevation=6.0,
          distance=3400.0, travelSeconds=6.0, arcLift=140.0, curvature=80.0)),
    ("Magenta Blue", "Burst Magenta", 21.6, 6.8,
     dict(startAzimuth=72.0, startElevation=24.0, endAzimuth=18.0, endElevation=4.0,
          distance=3000.0, travelSeconds=5.6, arcLift=160.0, curvature=-90.0)),
    ("Subtle Shooting Star", "Burst Spark", 23.0, 5.0,
     dict(startAzimuth=34.0, startElevation=31.0, endAzimuth=62.0, endElevation=15.0,
          distance=1900.0, travelSeconds=2.4, arcLift=50.0, curvature=0.0)),
]


def sky_direction(azimuth_deg, elevation_deg):
    """The same parameterisation `world::directionFromSky` uses: azimuth clockwise from +Z."""
    az = math.radians(azimuth_deg)
    el = math.radians(elevation_deg)
    horizontal = math.cos(el)
    return [horizontal * math.sin(az), math.sin(el), horizontal * math.cos(az)]


def preset(tool, style, name):
    out = subprocess.run([tool, style, name], capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("avgen_atmos_presets %r failed: %s" % (style, out.stderr.strip()))
    return json.loads(out.stdout)


def build_effects(tool):
    effects = []

    # ---- the aurora ----------------------------------------------------------------------------
    # Always on and fading up, because an aurora is scenery that breathes rather than an event. It
    # is anchored to the camera, which is what "an aurora surrounds the viewer" means: the curtains
    # keep their bearing as the dolly crosses the valley, while the comets -- anchored to the world
    # -- slide against them. The two anchoring modes in one shot is the parallax demonstration.
    aurora = preset(tool, "Glowmere Bioluminescence", "Valley Aurora")
    aurora["timing"].update(dict(fadeIn=3.0, fadeOut=0.0, windowStart=0.0, windowSeconds=0.0))
    aurora["aurora"]["shape"].update(dict(
        anchor="camera",
        curtainCount=4.0,
        radius=5200.0,
        layerSpacing=0.34,
        # Below the valley floor, so the curtain feet are hidden behind terrain rather than ending
        # in mid-air. The depth test does the rest: there is no horizon to author.
        baseHeight=-120.0,
        curtainHeight=4200.0,
    ))
    aurora["aurora"]["appearance"].update(dict(intensity=3.6, edgeBrightness=3.2, horizonGlow=0.75))
    aurora["aurora"]["audio"].update(dict(
        bass=0.95, lowMid=0.60, mid=0.50, high=0.80, beat=0.40,
        sensitivity=1.15, spectrumShape=0.80,
    ))
    aurora["ground"].update(dict(mode="subtle", color=[0.16, 0.74, 0.60], intensity=0.55))
    effects.append(aurora)

    # ---- the comets ----------------------------------------------------------------------------
    for style, name, start, seconds, path in COMETS:
        comet = preset(tool, style, name)
        # **Parked, and launched by the sequencer.** The window starts past the end of the piece, so
        # nothing fires until `comet.*.launch` moves it in. That makes section 7's "sequencer-
        # controlled comet event" a real demonstration rather than an event that writes the value
        # the file already had -- which would be indistinguishable from no sequencer at all.
        comet["timing"].update(dict(windowStart=3000.0, windowSeconds=seconds))
        comet["comet"]["path"].update(path)
        # The hero comet is the one section 6 is about: a low, bright, close pass that has something
        # to say to the ground. The burst comets are further off and leave the valley alone, which
        # is what stops three simultaneous washes flattening the scene.
        if name == "Hero Comet":
            comet["ground"].update(dict(mode="strong", color=[0.34, 0.86, 1.0],
                                        intensity=0.85, radius=520.0, falloff=2.2))
        elif name == "Rainbow Comet":
            comet["ground"].update(dict(mode="subtle", color=[0.70, 0.45, 1.0], intensity=0.6))
        else:
            comet["ground"]["mode"] = "off"
        effects.append(comet)
    return effects


def camera_keys():
    """Position and target tracks: a straight dolly with the aim held at a fixed bearing."""
    steps = 61  # one key every half second; smooth interpolation does the rest
    position, target = [], []
    for i in range(steps):
        t = i / (steps - 1)
        seconds = t * DURATION
        pos = [CAM_START[k] + (CAM_END[k] - CAM_START[k]) * t for k in range(3)]
        aim = sky_direction(AIM_AZIMUTH, AIM_ELEVATION)
        tgt = [pos[k] + aim[k] * AIM_DISTANCE for k in range(3)]
        position.append({"time": seconds, "value": pos, "interp": "smooth"})
        target.append({"time": seconds, "value": tgt, "interp": "smooth"})
    return position, target


def routes(effects):
    """The audio routes, in the engine's own default shapes.

    Mirrors `world::defaultEffectRoutes`. It is written out rather than called because a
    project file needs the routes as data and the engine installs none of its own -- section 8 asks
    for the effects to be modulatable, and this is what makes the shipped example actually move.
    """
    out = []

    def add(source, target, amount, attack, decay):
        out.append({
            "source": source, "target": target, "component": -1, "amount": amount,
            # `add` so silence leaves the authored pose exactly as written: an unplayed project
            # should look like what somebody authored, not like a collapsed one.
            "op": "add", "polarity": "unipolar", "enabled": True,
            "chain": {"attackMs": attack, "decayMs": decay},
        })

    aurora = "atmos/Valley Aurora/"
    add("audio.bass", aurora + "curtainHeight", 900.0, 60.0, 420.0)
    add("audio.rms", aurora + "intensity", 0.8, 80.0, 500.0)
    add("audio.lowMid", aurora + "waveAmplitude", 0.12, 50.0, 380.0)
    add("audio.mid", aurora + "turbulence", 0.20, 40.0, 320.0)
    add("audio.treble", aurora + "filaments", 0.55, 25.0, 240.0)
    add("beat.pulse", aurora + "edgeBrightness", 1.1, 10.0, 260.0)

    for _, name, _, _, _ in COMETS:
        base = "atmos/%s/" % name
        add("audio.rms", base + "coreIntensity", 6.0, 60.0, 400.0)
        add("beat.pulse", base + "tailIntensity", 1.4, 10.0, 280.0)
        add("audio.treble", base + "sparkleIntensity", 4.0, 20.0, 220.0)
    return out


def sequence():
    """The sequencer's half (brief section 7).

    Every one of these is `EventActionKind::SetParameter` aimed at an `atmos/<name>/<property>`
    path, which is the whole of "use the existing timeline/event infrastructure": the events bake to
    `params::Track` keys through `bakeEventFirings` exactly as a fog-density event does, and there
    is no atmospheric-effect verb because there does not need to be one.
    """
    def event(ident, time, target, value, seconds=0.0, hold=0.0):
        return {
            "id": ident,
            # The trigger's key is "time", not "timeSeconds" -- see seq/events.cpp:208. Getting this
            # wrong is silent: every event lands at t = 0 and the whole arrangement fires at once.
            "when": {"kind": "time", "time": time},
            "what": {"kind": "setParameter", "target": target, "amount": [value, 0.0, 0.0, 0.0],
                     "component": 0, "seconds": seconds, "hold": hold,
                     "interp": "smooth", "mode": "replace"},
            "enabled": True, "priority": 0,
        }

    # **Baselines first.** A `replace` event with nothing before it holds its destination value
    # backwards to t = 0, so an "intensity rises at 14 s" event without one is an intensity that was
    # already risen at t = 0 and never ramps. The engine warns about exactly this; these are the key
    # it asks for. Authored at t = 0 with the value the scene already states, so they change nothing
    # except giving every ramp below something to ramp *from*.
    events = [
        event("aurora.base", 0.0, "atmos/Valley Aurora/intensity", 3.6),
        event("aurora.base.top", 0.0, "atmos/Valley Aurora/topColor", 0.58),
        event("comet.hero.base", 0.0, "atmos/Hero Comet/speed", 1.0),
    ]
    # Each comet's window starts parked past the end of the piece, and stays parked until its launch
    # event moves it in. Without these baselines the launch value holds *backwards* to t = 0 -- the
    # engine warns about exactly that -- and the comet would appear on its own schedule whether or
    # not the sequencer ever fired, which is a demonstration of nothing.
    for _, name, _, _, _ in COMETS:
        events.append(event("%s.parked" % name.lower().replace(" ", "."), 0.0,
                            "atmos/%s/windowStart" % name, 3000.0))
    events += [
        # Aurora intensity transition: a swell into the second half of the piece and a settle after.
        event("aurora.swell", 14.0, "atmos/Valley Aurora/intensity", 4.6, seconds=3.0),
        event("aurora.settle", 26.5, "atmos/Valley Aurora/intensity", 2.4, seconds=3.0),
        # Aurora colour transition: the curtain's top drifts violet as the comets arrive.
        event("aurora.violet", 15.0, "atmos/Valley Aurora/topColor", 0.92, seconds=4.0),
        # Comet launch, authored as a window move rather than as a new verb: the effect is already
        # there and dormant, and starting it is one number.
        event("comet.hero.launch", 5.5, "atmos/Hero Comet/windowStart", 6.0),
        event("comet.rainbow.launch", 14.5, "atmos/Rainbow Comet/windowStart", 15.0),
        # Comet burst: three launches inside two and a half seconds.
        event("comet.burst.1", 20.0, "atmos/Burst Emerald/windowStart", 20.5),
        event("comet.burst.2", 20.0, "atmos/Burst Magenta/windowStart", 21.6),
        event("comet.burst.3", 20.0, "atmos/Burst Spark/windowStart", 23.0),
        # Comet speed change on the hero, so section 7's "speed changes" has a demonstration.
        event("comet.hero.accelerate", 9.0, "atmos/Hero Comet/speed", 1.25, seconds=1.5),
        # Aurora fade-out at the very end.
        event("aurora.fadeout", 28.5, "atmos/Valley Aurora/intensity", 0.6, seconds=1.5),
    ]
    return {"events": events}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--presets", default=os.path.join(REPO, "build/release/tools/avgen_atmos_presets"))
    args = parser.parse_args()
    if not os.path.exists(args.presets):
        sys.exit("avgen_atmos_presets not found at %s; build it first" % args.presets)

    # ---- the scene ----
    scene = json.load(open(SRC_SCENE))
    scene["name"] = "Glowmere Atmospherics"
    scene["atmosphericEffects"] = build_effects(args.presets)
    # The world effects Glowmere ships are gated on a director's cut this demonstration does not
    # have, so they would never fire. Left in place rather than removed: they are part of what
    # Glowmere is, and an empty `cameraShotSpans` is already the honest "nothing is directing".
    with open(OUT_SCENE, "w") as f:
        json.dump(scene, f, indent=2)
        f.write("\n")

    raw = open(OUT_SCENE, "rb").read()
    digest, size = hashlib.sha256(raw).hexdigest(), len(raw)

    # ---- the project ----
    proj = json.load(open(SRC_PROJ))
    proj["assets"]["scene"]["path"] = {
        "path": "glowmere-atmospherics.scene.json", "sha256": digest, "size": size,
    }
    position, target = camera_keys()
    # Only the camera tracks are replaced. The lens tracks are Glowmere's and are keyed out past
    # 199 s, which is harmless inside thirty seconds and is one fewer thing to have re-derived.
    keep = [t for t in proj["timeline"]["tracks"]
            if t["target"] not in ("camera/position", "camera/target")]
    proj["timeline"]["tracks"] = keep + [
        {"target": "camera/position", "component": -1, "timeBase": "seconds", "mode": "replace",
         "loopLength": 0.0, "enabled": True, "keys": position},
        {"target": "camera/target", "component": -1, "timeBase": "seconds", "mode": "replace",
         "loopLength": 0.0, "enabled": True, "keys": target},
    ]
    # Nothing is directing this camera, so the cut-gated machinery is emptied rather than left
    # pointing at Glowmere's 253-second arrangement.
    proj["cameraAimFollow"] = []
    proj["cameraShotSpans"] = []
    proj["routes"] = proj.get("routes", []) + routes(build_effects(args.presets))
    proj["sequence"] = sequence()
    proj["render"] = {
        "backend": "auto", "codec": "h264", "fps": 60, "width": 1920, "height": 1080,
        "output": "video", "outputPath": "glowmere-atmospherics.mp4", "quality": 88,
        "startSeconds": 0.0, "endSeconds": DURATION, "tier": "offline", "muxAudio": True,
        "limits": "tier",
    }
    # The camera is authored here, so the parameter table's stale camera pose must not fight it.
    for key, value in (("camera/position", CAM_START),
                       ("camera/target", [CAM_START[k] + sky_direction(AIM_AZIMUTH, AIM_ELEVATION)[k] * AIM_DISTANCE
                                          for k in range(3)])):
        proj["parameters"][key] = value

    with open(OUT_PROJ, "w") as f:
        json.dump(proj, f, indent=2)
        f.write("\n")

    print("glowmere-atmospherics.scene.json: %s %d bytes, %d atmospheric effect(s)"
          % (digest[:16], size, len(scene["atmosphericEffects"])))
    print("glowmere-atmospherics.json: %d route(s), %d sequence event(s)"
          % (len(proj["routes"]), len(proj["sequence"]["events"])))


if __name__ == "__main__":
    main()
