// Phase C §67: the multi-character demonstration. 10, 50 and 100 scouts, every one on the matcher,
// wandering on terrain in the ADR-623 match lab's valley, sharing one database. Generated by
// `tools/gen_match_crowd.py`.
//
// What is asserted is what a crowd can get wrong that one character cannot: that every body is
// matched (none silently fell back), that there is one database and not N, that the crowd is not
// in lockstep (the same clip at the same time is one character drawn N times), and that bodies
// stay on the ground. The update cost per frame is reported, and it is marked under load unless
// the machine was quiet.

#include "assets/asset_registry.hpp"
#include "core/time.hpp"
#include "params/modulation.hpp"
#include "params/parameter_set.hpp"
#include "scene/composition.hpp"
#include "signals/signal_bus.hpp"
#include "world/terrain_query.hpp"

#include <catch2/catch_test_macros.hpp>

#include <fmt/format.h>

#include <chrono>
#include <filesystem>
#include <set>

using namespace avgen;
namespace fs = std::filesystem;

TEST_CASE("§67 a crowd of matched scouts: all matched, one database, not in lockstep", "[crowd][motionmatching][aliens][phaseC]") {
    if (!fs::exists(fs::path(AVGEN_SOURCE_DIR) / "assets" / "aliens" / "alien-scout.glb")) {
        SKIP("the scout is not present");
    }
    std::string report = "  N  matched  databases  distinct(clip,sample)  ms/frame (under load unless noted)\n";
    for (const int n : {10, 50, 100}) {
        const fs::path file = fs::path(AVGEN_SOURCE_DIR) / "examples" / "labs" / "motionmatch" /
                              fmt::format("glowmere-match-crowd-{}.scene.json", n);
        assets::AssetRegistry registry(file.parent_path());
        auto loaded = scene::Composition::loadFile(file, registry);
        REQUIRE(loaded.has_value());
        scene::Composition& comp = **loaded;
        params::ParameterSet params;
        params::Modulator modulator;
        signals::SignalBus bus;
        comp.attach(params, modulator);
        comp.setViewport(320, 180);
        comp.scene().detailLimits.entityDistanceCull = false;
        REQUIRE(comp.entityWorld().size() == static_cast<std::size_t>(n));

        constexpr int kFrames = 240;
        double seconds = 0.0;
        int matchedFrames = 0;
        int bodyFrames = 0;
        std::set<std::uint32_t> lastSelections;
        float worstDrop = 0.0f;
        for (int f = 0; f < kFrames; ++f) {
            FrameTime time;
            time.renderTime = static_cast<double>(f) / 60.0;
            time.deltaTime = f == 0 ? 0.0 : 1.0 / 60.0;
            time.frameIndex = static_cast<std::uint64_t>(f);
            const auto t0 = std::chrono::steady_clock::now();
            params.resetFinals();
            comp.updateFields(time, bus, modulator);
            modulator.applyRoutes(bus, params, time.deltaTime);
            comp.updateBehaviour(time, bus);
            comp.update(time);
            seconds += std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
        }
        // The last frame, body by body.
        const world::TerrainQuery terrain = comp.terrainQuery();
        REQUIRE(terrain.valid());
        for (int i = 0; i < n; ++i) {
            const entity::Entity* e = comp.entityWorld().find(fmt::format("scout-{:03d}", i));
            REQUIRE(e != nullptr);
            ++bodyFrames;
            matchedFrames += e->motionChainResult().provider == 0 ? 1 : 0;
            lastSelections.insert(e->motionMemory().selection);
            const glm::vec3 p = e->state().position();
            worstDrop = std::max(worstDrop, std::abs(p.y - terrain.heightAt(glm::vec2(p.x, p.z))));
        }
        report += fmt::format("{:>3}  {:>7}  {:>9}  {:>21}  {:8.2f}   worst |y - ground| {:.3f}\n", n, matchedFrames,
                              comp.motionDatabaseCount(), lastSelections.size(), 1000.0 * seconds / kFrames, worstDrop);
        CHECK(matchedFrames == bodyFrames);
        CHECK(comp.motionDatabaseCount() == 1u);
        // Not lockstep: at least a third of the crowd is on a sample no one else is on.
        CHECK(lastSelections.size() * 3u >= static_cast<std::size_t>(n));
        CHECK(worstDrop < 0.5f);
    }
    WARN(report);
}
